// Generated from MSN Finance API - 898 Indonesian stock IDs (896 unique tickers)
// Last updated: 2026-02-16
// Note: Some tickers map to multiple IDs (e.g., SOUL has 3 IDs)

package msn

// IDXStock represents an Indonesian stock listing
type IDXStock struct {
	ID   string // MSN internal ID
	Name string // Short company name
}

// IDXStocks maps ticker symbols to MSN stock info
// Use GetIDXStock(ticker) to look up a stock
var IDXStocks = map[string]IDXStock{
	"AADI": {ID: "cfatz2", Name: "Adaro Andalan"},
	"AALI": {ID: "bn8zk2", Name: "Astra Agro"},
	"ABBA": {ID: "bkf9ec", Name: "Mahaka Media"},
	"ABDA": {ID: "bkf9h7", Name: "Asuransi ABDA"},
	"ABMM": {ID: "bkf9k2", Name: "ABM Investama"},
	"ACES": {ID: "bn8zyc", Name: "Aspiration Life"},
	"ACRO": {ID: "cc48gh", Name: "Samcro Hyosung"},
	"ACST": {ID: "bkf9pr", Name: "Acset Indonusa"},
	"ADCP": {ID: "c59mf2", Name: "Adhi Commuter"},
	"ADES": {ID: "bkf9sm", Name: "Akasha Wira Intl"},
	"ADHI": {ID: "bn9127", Name: "Adhi Karya"},
	"ADMF": {ID: "bkf9yc", Name: "Adira Finance"},
	"ADMG": {ID: "bn9152", Name: "Polychem IDN"},
	"ADMR": {ID: "c4pl52", Name: "Alamtri Miner"},
	"ADRO": {ID: "bn917w", Name: "Alamtri Rsrcs"},
	"AEGS": {ID: "carobh", Name: "Anugerah Sparepa"},
	"AGAR": {ID: "bsu9xm", Name: "Asia Sejahtera"},
	"AGII": {ID: "bkfa7w", Name: "Samator Indo Gas"},
	"AGRO": {ID: "bkfaar", Name: "Bank Raya"},
	"AGRS": {ID: "bkfadm", Name: "Bank IBK"},
	"AHAP": {ID: "bkfagh", Name: "Asuransi Harta"},
	"AIMS": {ID: "bkfajc", Name: "Artha Mahiya Inv"},
	"AISA": {ID: "bkfam7", Name: "FKS Food Sejahte"},
	"AKKU": {ID: "bkfctc", Name: "Anugerah Kagum"},
	"AKPI": {ID: "bkfcw7", Name: "Argha Karya"},
	"AKRA": {ID: "bkfcz2", Name: "AKR Corporindo"},
	"AKSI": {ID: "bkfd2w", Name: "Mineral Sumberda"},
	"ALDO": {ID: "bkfd5r", Name: "Alkindo Naratama"},
	"ALII": {ID: "ccanzr", Name: "Ancara Logistics"},
	"ALKA": {ID: "bkfd8m", Name: "Alakasa Industri"},
	"ALMI": {ID: "bkfdbh", Name: "Alumindo Light"},
	"ALTO": {ID: "bkfdec", Name: "Tri Banyan Tirta"},
	"AMAG": {ID: "bkfchw", Name: "Asuransi MAG"},
	"AMAN": {ID: "btysar", Name: "Makmur Berkah"},
	"AMAR": {ID: "btf6a2", Name: "Bk Amar"},
	"AMFG": {ID: "bkfckr", Name: "Asahimas Flat"},
	"AMIN": {ID: "bkfcnm", Name: "Atmindo"},
	"AMMN": {ID: "ca993m", Name: "Amman Mineral In"},
	"AMMS": {ID: "c6yaw7", Name: "Agung Menjangan"},
	"AMOR": {ID: "btfbw7", Name: "Ashmore Asset"},
	"AMRT": {ID: "bkfcqh", Name: "Sumber Alfaria"},
	"ANDI": {ID: "bgrwf2", Name: "Andira Agro"},
	"ANJT": {ID: "bkfem7", Name: "Austindo"},
	"ANTM": {ID: "bn8zmw", Name: "ANTM"},
	"APEX": {ID: "bkferw", Name: "Apexindo Pratama"},
	"APIC": {ID: "bkfeur", Name: "Pac Strategic"},
	"APII": {ID: "bkfexm", Name: "Arita Prima ID"},
	"APLI": {ID: "bkff1h", Name: "Asiaplast Inds"},
	"APLN": {ID: "bkff4c", Name: "Agung Podomoro"},
	"ARCI": {ID: "c2il1h", Name: "Archi Indonesia"},
	"AREA": {ID: "ccsom7", Name: "Dunia Virtual"},
	"ARGO": {ID: "bkff77", Name: "Argo Pantes"},
	"ARII": {ID: "bkffa2", Name: "Atlas Resources"},
	"ARKA": {ID: "bqtwtc", Name: "Arkha Jayanti"},
	"ARKO": {ID: "c6qaqh", Name: "Arkora Hydro"},
	"ARNA": {ID: "bkfffr", Name: "Arwana"},
	"ARTA": {ID: "bkffim", Name: "Arthavest"},
	"ARTO": {ID: "bkffoc", Name: "Bank Jago"},
	"ASBI": {ID: "bkffzr", Name: "Asuransi Bintang"},
	"ASDM": {ID: "bkfg3m", Name: "Asuransi Dayin"},
	"ASGR": {ID: "bkfg6h", Name: "Astra Graphia"},
	"ASHA": {ID: "c6a3yc", Name: "Cilacap Samudera"},
	"ASII": {ID: "bn91gh", Name: "Astra Intl"},
	"ASJT": {ID: "bkfgc7", Name: "Asuransi Jastan"},
	"ASLC": {ID: "c4xl52", Name: "Autopedia Sukses"},
	"ASLI": {ID: "cc41ww", Name: "Asri Karya"},
	"ASMI": {ID: "bkfgf2", Name: "Asuransi Maximus"},
	"ASPI": {ID: "btr8pr", Name: "Andalan Sakti"},
	"ASPR": {ID: "chbyjc", Name: "Asia Pramulia"},
	"ASRI": {ID: "bkfghw", Name: "Alam Sutera Rlty"},
	"ASRM": {ID: "bkfgkr", Name: "Asuransi Rmyn"},
	"ASSA": {ID: "bkfgnm", Name: "Adi Sarana"},
	"ATAP": {ID: "bwzup2", Name: "Trimitra Prawara"},
	"ATIC": {ID: "bkffr7", Name: "Anabatic Tech"},
	"ATLA": {ID: "ccwjvh", Name: "Atlantis Subsea"},
	"AUTO": {ID: "bkffu2", Name: "Astra Otoparts"},
	"AVIA": {ID: "c4bepr", Name: "Avia Avian Pt"},
	"AWAN": {ID: "c9f9yc", Name: "PT Era Digital"},
	"AXIO": {ID: "c6v4pr", Name: "Tera Data"},
	"AYAM": {ID: "cbkfkr", Name: "JANU PUTRA"},
	"AYLS": {ID: "btox8m", Name: "Agro Yasa"},
	"BABP": {ID: "bkfgqh", Name: "Bank MNC"},
	"BABY": {ID: "carnqh", Name: "Multitrend Indo"},
	"BACA": {ID: "bkfgtc", Name: "Bank Capital ID"},
	"BAIK": {ID: "ccbzar", Name: "Bersama Menca"},
	"BAJA": {ID: "bkfgw7", Name: "Saranacentral"},
	"BALI": {ID: "bkfgz2", Name: "Bali Towerindo"},
	"BANK": {ID: "bxjrc7", Name: "PT Bank Aladin"},
	"BAPA": {ID: "bkfh2w", Name: "Bekasi Asri"},
	"BAPI": {ID: "breeur", Name: "Bhakti Agung"},
	"BATA": {ID: "bkflyc", Name: "Sepatu Bata"},
	"BATR": {ID: "cddzvh", Name: "Benteng Api Tech"},
	"BAUT": {ID: "c4xpm7", Name: "Mitra Angkasa"},
	"BAYU": {ID: "bkfm27", Name: "Bayu Buana"},
	"BBCA": {ID: "bn91jc", Name: "Bank Cntrl Asia"},
	"BBHI": {ID: "bkfm7w", Name: "Allo Bank"},
	"BBKP": {ID: "bkfmar", Name: "Bank KB"},
	"BBLD": {ID: "bkfmdm", Name: "Buana Finance"},
	"BBMD": {ID: "bkfmgh", Name: "Bank Mestika"},
	"BBNI": {ID: "bn91m7", Name: "Bank BNI"},
	"BBRI": {ID: "bn91p2", Name: "Bank BRI"},
	"BBRM": {ID: "bkfmrw", Name: "Bina Buana Raya"},
	"BBSI": {ID: "bvpgvh", Name: "Krom Bank"},
	"BBSS": {ID: "bu9cqh", Name: "Bumi Benowo"},
	"BBTN": {ID: "bkfmur", Name: "Bank BTN"},
	"BBYB": {ID: "bkfmxm", Name: "PT Bank Neo"},
	"BCAP": {ID: "bkfn1h", Name: "MNC Kapital ID"},
	"BCIC": {ID: "bgt4rw", Name: "Bank JTrust ID"},
	"BCIP": {ID: "bkfn4c", Name: "Bumi Citra"},
	"BDKR": {ID: "c8zmyc", Name: "Berdikari Pondas"},
	"BDMN": {ID: "bn91rw", Name: "Bank Danamon"},
	"BEBS": {ID: "bzv7ar", Name: "Berkah Beton"},
	"BEEF": {ID: "bokavh", Name: "Estika Tata"},
	"BEER": {ID: "c8if77", Name: "Jobubu Jarum"},
	"BEKS": {ID: "bkfna2", Name: "Bank Banten"},
	"BELI": {ID: "c7svnm", Name: "Global Digital"},
	"BELL": {ID: "bkfncw", Name: "Trisula Textile"},
	"BESS": {ID: "btyakr", Name: "Batulicin"},
	"BEST": {ID: "bkfh5r", Name: "Bekasi Fajar"},
	"BFIN": {ID: "bkfh8m", Name: "BFI Finance ID"},
	"BGTG": {ID: "bkfhbh", Name: "Bank Ganesha"},
	"BHAT": {ID: "bua6k2", Name: "Bhakti Multi"},
	"BHIT": {ID: "bkfhec", Name: "MNC Asia Hldg"},
	"BIKE": {ID: "c5iucw", Name: "Sepeda Bersama"},
	"BIMA": {ID: "bkfkz2", Name: "Primarindo Asia"},
	"BINA": {ID: "bn92u2", Name: "Bank Ina"},
	"BINO": {ID: "c45tp2", Name: "Perma Plasindo"},
	"BIPI": {ID: "bn92ww", Name: "Astrindo Nusan"},
	"BIPP": {ID: "bkfl8m", Name: "Bhuwanatala Inda"},
	"BIRD": {ID: "bkflbh", Name: "Blue Brd"},
	"BISI": {ID: "bn92zr", Name: "BISI Intl"},
	"BJBR": {ID: "bkflh7", Name: "Bank BJB"},
	"BJTM": {ID: "bn936h", Name: "Bank Jatim"},
	"BKDP": {ID: "bkflmw", Name: "Bukit Darmo"},
	"BKSL": {ID: "bkflpr", Name: "Sentul City"},
	"BKSW": {ID: "bkflsm", Name: "Bank QNB ID"},
	"BLES": {ID: "cdlvh7", Name: "Superior Prima"},
	"BLOG": {ID: "chc7m7", Name: "Trimitra Trans"},
	"BLTA": {ID: "bgt5u2", Name: "Berlian Laju"},
	"BLTZ": {ID: "bkflvh", Name: "Graha Layar"},
	"BLUE": {ID: "bqrgar", Name: "Berkah Prima"},
	"BMAS": {ID: "bkfoqh", Name: "Bank Maspion ID"},
	"BMBL": {ID: "c8isqh", Name: "Lavender Bina"},
	"BMHS": {ID: "c2md4c", Name: "Bundamedik"},
	"BMRI": {ID: "bn939c", Name: "Bank Mandiri"},
	"BMSR": {ID: "bkfow7", Name: "Bintang Mitra"},
	"BMTR": {ID: "bkfoz2", Name: "Global Mediacom"},
	"BNBA": {ID: "bkfp2w", Name: "Bank Bumi Arta"},
	"BNBR": {ID: "bn93c7", Name: "Bakrie& Brothers"},
	"BNGA": {ID: "bkfp8m", Name: "Bank CIMB Niaga"},
	"BNII": {ID: "bn93f2", Name: "Bank Maybank ID"},
	"BNLI": {ID: "bn93hw", Name: "Bank Permata"},
	"BOAT": {ID: "cf4yu2", Name: "Newport Marine"},
	"BOBA": {ID: "c3wioc", Name: "Formosa"},
	"BOGA": {ID: "bkfph7", Name: "Apollo Glo"},
	"BOLA": {ID: "bqe3p2", Name: "Bali Bintang"},
	"BOLT": {ID: "bkfpk2", Name: "Garuda Metalindo"},
	"BPFI": {ID: "bkfppr", Name: "Woori Finance"},
	"BPII": {ID: "bkfpsm", Name: "Batavia Prosperi"},
	"BPTR": {ID: "bgth1h", Name: "Batavia"},
	"BRAM": {ID: "bkfpvh", Name: "Indo Kordsa"},
	"BREN": {ID: "cb1ra2", Name: "Barito Renewable"},
	"BRIS": {ID: "bgtha2", Name: "Bank BRISyariah"},
	"BRMS": {ID: "bn924c", Name: "Bumi Resource Mn"},
	"BRNA": {ID: "bkfq27", Name: "Berlina"},
	"BRPT": {ID: "bn9277", Name: "Barito Pacific"},
	"BRRC": {ID: "cflfa2", Name: "Raja Roti"},
	"BSBK": {ID: "c7svhw", Name: "Wulandari Bangun"},
	"BSDE": {ID: "bkfq7w", Name: "Bumi Serpong"},
	"BSIM": {ID: "bn92a2", Name: "Bank Sinarmas"},
	"BSML": {ID: "c4is3m", Name: "Bintang Samudera"},
	"BSSR": {ID: "bkfqdm", Name: "Baramulti Sukses"},
	"BSWD": {ID: "bkfqgh", Name: "Bank Of India ID"},
	"BTEK": {ID: "bkfqjc", Name: "Bumi Teknokultur"},
	"BTON": {ID: "bkfqp2", Name: "Betonjaya"},
	"BTPN": {ID: "bkfqrw", Name: "Bank SMBC"},
	"BTPS": {ID: "bgtwjc", Name: "Bank BTPN ID"},
	"BUAH": {ID: "c71dyc", Name: "Segar Kumala"},
	"BUDI": {ID: "bkfqur", Name: "Budi Starch"},
	"BUKA": {ID: "c2wgkr", Name: "Bukalapak.com"},
	"BUKK": {ID: "bkfqxm", Name: "Bukaka Teknik"},
	"BULL": {ID: "bkfnu2", Name: "BULL Indonesia"},
	"BUMI": {ID: "bn92fr", Name: "Bumi Resources"},
	"BUVA": {ID: "bkfnzr", Name: "Bukit Uluwatu"},
	"BVIC": {ID: "bkfo3m", Name: "Bank Victoria"},
	"BWPT": {ID: "bn92im", Name: "Eagle High Plnt"},
	"BYAN": {ID: "bn92lh", Name: "Bayan Resources"},
	"CAKK": {ID: "bne4c7", Name: "Cahayaputra Asa"},
	"CAMP": {ID: "bkfoc7", Name: "Campina Ice"},
	"CANI": {ID: "bkfof2", Name: "Capitol Nusan"},
	"CARE": {ID: "btysdm", Name: "Metro Healthcare"},
	"CARS": {ID: "bkfohw", Name: "Industri Dan"},
	"CASA": {ID: "bkfokr", Name: "Capital Fincl ID"},
	"CASH": {ID: "bufc7w", Name: "Cashlez"},
	"CASS": {ID: "bkfonm", Name: "Cahaya Aero"},
	"CBDK": {ID: "cflejc", Name: "Bangun Kosambi"},
	"CBPE": {ID: "c8ipmw", Name: "PT Citra Buana"},
	"CBRE": {ID: "c8ifww", Name: "Cakra Buana Reso"},
	"CBUT": {ID: "c7sxgh", Name: "CBUT"},
	"CCSI": {ID: "bqh6ar", Name: "Commn Cbl Sys"},
	"CDIA": {ID: "chdaw7", Name: "Chandra Daya In"},
	"CEKA": {ID: "bkfkqh", Name: "Wilmar Cahaya ID"},
	"CENT": {ID: "bkfktc", Name: "Centratama Tele"},
	"CFIN": {ID: "bkfkw7", Name: "Clipan Finance"},
	"CGAS": {ID: "cc45zr", Name: "Citra Nusantara"},
	"CHEK": {ID: "chddzr", Name: "Diastika Bioteki"},
	"CHEM": {ID: "c6qahw", Name: "Chemstar"},
	"CHIP": {ID: "c8qlmw", Name: "Pelita Teknologi"},
	"CINT": {ID: "bkfnfr", Name: "Chitose"},
	"CITA": {ID: "bkfnim", Name: "Cita Mineral"},
	"CITY": {ID: "bjs6w7", Name: "Natura City Devs"},
	"CLAY": {ID: "bona52", Name: "Citra Putra"},
	"CLEO": {ID: "bkfnoc", Name: "Sariguna"},
	"CLPI": {ID: "bkfnr7", Name: "Colorpak ID"},
	"CMNP": {ID: "bn93kr", Name: "Citra Marga Nusa"},
	"CMNT": {ID: "c3bxcw", Name: "Cemindo Gemilang"},
	"CMPP": {ID: "bkgku2", Name: "AirAsia Indo"},
	"CMRY": {ID: "c4b81h", Name: "Cisarua Mountain"},
	"CNKO": {ID: "bkgkzr", Name: "Exploitasi Energ"},
	"CNMA": {ID: "cagkkr", Name: "NSR"},
	"COAL": {ID: "c78lp2", Name: "Black Diamond"},
	"COCO": {ID: "bpfy1h", Name: "Wahana Interfood"},
	"COIN": {ID: "chc7p2", Name: "Indokripto Koin"},
	"CPIN": {ID: "bn93nm", Name: "Charoen Pokphand"},
	"CPRO": {ID: "bkgl9c", Name: "CP Prima"},
	"CRAB": {ID: "c71ep2", Name: "Toba Surimi Inds"},
	"CRSN": {ID: "ca9dnm", Name: "Carsurin"},
	"CSAP": {ID: "bn93z2", Name: "Catur Sentosa"},
	"CSIS": {ID: "bkglf2", Name: "CSIS"},
	"CSMI": {ID: "bua4a2", Name: "Cipta Selera"},
	"CSRA": {ID: "btf6cw", Name: "Cisadane Sawit"},
	"CTBN": {ID: "bkglhw", Name: "Citra Tubindo"},
	"CTRA": {ID: "bn942w", Name: "Ciputra Dvlpmt"},
	"CTTH": {ID: "bkglnm", Name: "Citatah"},
	"CUAN": {ID: "c8ztf2", Name: "Petrindo Jaya"},
	"CYBR": {ID: "caj9jc", Name: "Itsec Asia"},
	"DAAZ": {ID: "cf3dr7", Name: "Daaz Bara"},
	"DADA": {ID: "btov1h", Name: "Diamond Citra"},
	"DART": {ID: "bkglqh", Name: "Duta Anggada"},
	"DATA": {ID: "cd3e27", Name: "Remala Abadi"},
	"DAYA": {ID: "bkgltc", Name: "Duta Intidaya"},
	"DCII": {ID: "bxbr3m", Name: "DCI Indonesia"},
	"DEFI": {ID: "bkglw7", Name: "Danapac"},
	"DEPO": {ID: "c461k2", Name: "Caturkarda Depo"},
	"DEWA": {ID: "bn93qh", Name: "Darma Henwa"},
	"DEWI": {ID: "c6t4oc", Name: "Dewi Shri Farmin"},
	"DFAM": {ID: "bkgm2w", Name: "Dafam Property"},
	"DGIK": {ID: "bkgm5r", Name: "Nusa Konstruksi"},
	"DGNS": {ID: "bxbs2w", Name: "Diagnos"},
	"DGWG": {ID: "cfl46h", Name: "Delta Giri"},
	"DIGI": {ID: "bguqr7", Name: "Arkadia Dig"},
	"DILD": {ID: "bn93tc", Name: "Intiland Dvlpmt"},
	"DIVA": {ID: "bny8f2", Name: "Nusantara"},
	"DKFT": {ID: "bkgmbh", Name: "Central Omega"},
	"DKHH": {ID: "cgo8rw", Name: "Cipta Sarana Med"},
	"DLTA": {ID: "bkgn52", Name: "Delta Djakarta"},
	"DMAS": {ID: "bkgn7w", Name: "Puradelta Lestar"},
	"DMMX": {ID: "bsh6z2", Name: "Digital Mediatam"},
	"DMND": {ID: "bti2qh", Name: "Diamond Food"},
	"DNAR": {ID: "bkgnar", Name: "PT Bank Oke"},
	"DNET": {ID: "bkgndm", Name: "Indoritel Makmur"},
	"DOID": {ID: "bkgngh", Name: "BUMA Internasion"},
	"DOOH": {ID: "c9pg52", Name: "Era Media"},
	"DOSS": {ID: "cecd8m", Name: "Glo Sukses Dig"},
	"DPNS": {ID: "bkgnjc", Name: "Duta Pertiwi Nus"},
	"DPUM": {ID: "bkgnm7", Name: "Dua Putra Utama"},
	"DRMA": {ID: "c4is9c", Name: "Dharma Polimetal"},
	"DSFI": {ID: "bkgnp2", Name: "Dharma Samudera"},
	"DSNG": {ID: "bkgnrw", Name: "Dharma Satya"},
	"DSSA": {ID: "bn94ec", Name: "Dian Swastatika"},
	"DUTI": {ID: "bn94h7", Name: "Duta Pertiwi"},
	"DVLA": {ID: "bkgmsm", Name: "Darya-Varia"},
	"DWGL": {ID: "bkgmvh", Name: "Dwi Guna"},
	"DYAN": {ID: "bkgmyc", Name: "Dyandra Media"},
	"EAST": {ID: "bqrjmw", Name: "Eastparc Hotel"},
	"ECII": {ID: "bkgn27", Name: "Electronic City"},
	"EDGE": {ID: "bxmmkr", Name: "Indointernet"},
	"EKAD": {ID: "bkgmec", Name: "Ekadharma Intl"},
	"ELIT": {ID: "c8ifcw", Name: "Data Sinergitama"},
	"ELPI": {ID: "c71dh7", Name: "Pelayaran Nasion"},
	"ELSA": {ID: "bkgmh7", Name: "Elnusa"},
	"ELTY": {ID: "bn94k2", Name: "Bakrieland Dev"},
	"EMAS": {ID: "ci4x5r", Name: "Merdeka Gold Res"},
	"EMDE": {ID: "bkgo77", Name: "Megapolitan Dev"},
	"EMTK": {ID: "bkgocw", Name: "Emtek Indonesia"},
	"ENAK": {ID: "c53nww", Name: "Champ Resto"},
	"ENRG": {ID: "bkgofr", Name: "Energi Mega Pers"},
	"ENZO": {ID: "bvqna2", Name: "Morenzo Abadi"},
	"EPAC": {ID: "buzekr", Name: "Megalestari"},
	"EPMT": {ID: "bkgoim", Name: "Enseval Putera"},
	"ERAA": {ID: "bkgolh", Name: "Erajaya"},
	"ERAL": {ID: "cakb4c", Name: "Sinar Eka Selara"},
	"ERTX": {ID: "bkgooc", Name: "Eratex Djaja"},
	"ESIP": {ID: "bsq1dm", Name: "Sinergi Inti"},
	"ESSA": {ID: "bkgnxm", Name: "ESSA Industries"},
	"ESTA": {ID: "btxltc", Name: "Esta Multi Usaha"},
	"ESTI": {ID: "bkgo1h", Name: "Ever Shine Tex"},
	"EURO": {ID: "c6zylh", Name: "Estee Gold Feet"},
	"EXCL": {ID: "bn94pr", Name: "XLSMART Telecom"},
	"FAPA": {ID: "bx7mww", Name: "FAP Agri"},
	"FAST": {ID: "bkgor7", Name: "Fast Food ID"},
	"FASW": {ID: "bkgou2", Name: "Fajar Surya"},
	"FILM": {ID: "bgva7w", Name: "MD Ent"},
	"FIMP": {ID: "c1paqh", Name: "Fimperkasa Utama"},
	"FIRE": {ID: "bkgozr", Name: "AEI"},
	"FISH": {ID: "bkgp3m", Name: "FKS Multi Agro"},
	"FITT": {ID: "bqcw2w", Name: "Hotel Fitra Intl"},
	"FLMC": {ID: "c2p22w", Name: "Falmaco Nonwoven"},
	"FMII": {ID: "bkgp9c", Name: "Fortune Mate ID"},
	"FOLK": {ID: "caj9ar", Name: "Multi Garam Utam"},
	"FOOD": {ID: "bohgur", Name: "Sentra Food ID"},
	"FORE": {ID: "cghp7w", Name: "Fore Kopi"},
	"FORU": {ID: "bkgpc7", Name: "Fortune ID"},
	"FPNI": {ID: "bkgphw", Name: "Lotte Chem Titan"},
	"FUJI": {ID: "bqrhww", Name: "Fuji Finance ID"},
	"FUTR": {ID: "c8xc2w", Name: "PT Futura Energi"},
	"FWCT": {ID: "c8no4c", Name: "Wijaya Cahaya"},
	"GDST": {ID: "bkgpnm", Name: "Gunawan Dianjaya"},
	"GDYR": {ID: "bkgpqh", Name: "Goodyear"},
	"GEMA": {ID: "bkgptc", Name: "Gema Grahasarana"},
	"GEMS": {ID: "bkgpw7", Name: "Golden Energy"},
	"GGRM": {ID: "bn94vh", Name: "Gudang Garam"},
	"GGRP": {ID: "brivww", Name: "Gunung Raja"},
	"GHON": {ID: "bkgq2w", Name: "Gihon"},
	"GIAA": {ID: "bkgq5r", Name: "Garuda Indonesia"},
	"GJTL": {ID: "bn9527", Name: "Gajah Tunggal"},
	"GLOB": {ID: "bgveur", Name: "Globe Kita"},
	"GLVA": {ID: "bt94fr", Name: "Galva Tech"},
	"GMFI": {ID: "bkgqbh", Name: "GMF Aero Asia"},
	"GMTD": {ID: "bkgqk2", Name: "Gowa Makassar"},
	"GOLD": {ID: "bkgqmw", Name: "Visi"},
	"GOLF": {ID: "cdml52", Name: "Pt Intra"},
	"GOOD": {ID: "bkgqsm", Name: "Garudafood Putra"},
	"GOTO": {ID: "c5tv8m", Name: "Gojek"},
	"GPRA": {ID: "bkgqvh", Name: "Perdana Gapura"},
	"GPSO": {ID: "c39qp2", Name: "Geoprima Solusi"},
	"GRIA": {ID: "cakam7", Name: "Ingria Pratama"},
	"GRPH": {ID: "cc65vh", Name: "Griptha Putra"},
	"GRPM": {ID: "ca9bar", Name: "Graha Prima"},
	"GSMF": {ID: "bkgqec", Name: "Eqty Dvlpmt Inv"},
	"GTBO": {ID: "bkgqh7", Name: "Garda Tujuh"},
	"GTRA": {ID: "c9a7c7", Name: "Grahaprima"},
	"GTSI": {ID: "c3atkr", Name: "Gts Internasiona"},
	"GULA": {ID: "c6ybbh", Name: "Aman Agrindo"},
	"GUNA": {ID: "cdm6oc", Name: "PT Gunanusa"},
	"GWSA": {ID: "bkgqyc", Name: "Greenwood Sejaht"},
	"GZCO": {ID: "bkgr27", Name: "Gozco Plantation"},
	"HADE": {ID: "bkgr52", Name: "Himalaya EP"},
	"HAIS": {ID: "c3839c", Name: "Hasnur"},
	"HAJJ": {ID: "c9c9z2", Name: "Arsy Buana"},
	"HALO": {ID: "c8snbh", Name: "Haloni Jane"},
	"HATM": {ID: "c6vxxm", Name: "Habco Trans"},
	"HBAT": {ID: "caj5ur", Name: "Minahasa"},
	"HDFA": {ID: "bkgr7w", Name: "Radana Bhaskara"},
	"HDIT": {ID: "bqsr9c", Name: "Hensel Davest"},
	"HEAL": {ID: "bgvigh", Name: "Mediakaloka"},
	"HELI": {ID: "bkgrdm", Name: "Jaya Trishindo"},
	"HERO": {ID: "bkgrgh", Name: "DFI Retail"},
	"HEXA": {ID: "bn95ar", Name: "Hexindo Adiperka"},
	"HGII": {ID: "cfl3r7", Name: "Hero Global Inv"},
	"HILL": {ID: "c8xfhw", Name: "Hillcon"},
	"HITS": {ID: "bkgrm7", Name: "Humpuss Intermod"},
	"HMSP": {ID: "bn95jc", Name: "HM Sampoerna"},
	"HOKI": {ID: "bkgrur", Name: "Buyung Poetra"},
	"HOMI": {ID: "bvpl7w", Name: "Grand House"},
	"HOPE": {ID: "c24y52", Name: "Harapan Duta"},
	"HRME": {ID: "bpplhw", Name: "Menteng Heritage"},
	"HRTA": {ID: "bkgs4c", Name: "Hartadinata"},
	"HRUM": {ID: "bn957w", Name: "Harum Energy"},
	"HUMI": {ID: "caj9p2", Name: "HUMI"},
	"HYGN": {ID: "ccbzjc", Name: "Ecocare Indo"},
	"IATA": {ID: "bkgsa2", Name: "PT MNC Energy"},
	"IBFN": {ID: "bkgscw", Name: "Intan Baru Prana"},
	"IBOS": {ID: "c5z1vh", Name: "Indo Boga Sukses"},
	"IBST": {ID: "bkgsfr", Name: "Inti Bangun"},
	"ICBP": {ID: "bkgsim", Name: "Indofood CBP"},
	"ICON": {ID: "bkgslh", Name: "Island Concepts"},
	"IDEA": {ID: "c3at9c", Name: "IDeA Indonesia"},
	"IDPR": {ID: "bkgsoc", Name: "Indopora"},
	"IFII": {ID: "bt26w7", Name: "Indonesia Fibre"},
	"IFSH": {ID: "bsua4c", Name: "Ifishdeco"},
	"IGAR": {ID: "bkgsr7", Name: "Champion Pacific"},
	"IKAI": {ID: "bkgsww", Name: "Intikeramik Alam"},
	"IKAN": {ID: "btov4c", Name: "EMC"},
	"IKBI": {ID: "bkgszr", Name: "Sumi Indo Kabel"},
	"IKPM": {ID: "cbetnm", Name: "Ikapharmindo"},
	"IMAS": {ID: "bkguk2", Name: "Indomobil Sukses"},
	"IMJS": {ID: "bkgumw", Name: "Indomobil Multi"},
	"IMPC": {ID: "bkgupr", Name: "Impack Pratama"},
	"INAI": {ID: "bkguvh", Name: "Indal Aluminium"},
	"INCF": {ID: "bkguyc", Name: "Indo Komoditi"},
	"INCI": {ID: "bkgv27", Name: "Intanwijaya Intl"},
	"INCO": {ID: "bn96cw", Name: "Vale Indonesia"},
	"INDF": {ID: "bn96fr", Name: "Indofood Sukses"},
	"INDO": {ID: "btf6ww", Name: "Royalindo Inv"},
	"INDR": {ID: "bkgvar", Name: "Indo-Rama"},
	"INDS": {ID: "bkgvdm", Name: "Indospring"},
	"INDX": {ID: "bkgvgh", Name: "Tanah Laut"},
	"INDY": {ID: "bkgvjc", Name: "Indika Energy"},
	"INET": {ID: "caehu2", Name: "Sinergi Inti"},
	"INKP": {ID: "bn96im", Name: "Indah Kiat"},
	"INOV": {ID: "bqtw6h", Name: "Inocycle"},
	"INPC": {ID: "bkgttc", Name: "Bank Artha Graha"},
	"INPP": {ID: "bkgtw7", Name: "ID Paradise"},
	"INPS": {ID: "bkgtz2", Name: "Indah Prakasa"},
	"INRU": {ID: "bkgu2w", Name: "Toba Pulp ID"},
	"INTA": {ID: "bkgu5r", Name: "Intraco Penta"},
	"INTD": {ID: "bkgu8m", Name: "Inter Delta"},
	"INTP": {ID: "bn95m7", Name: "Indocement"},
	"IOTF": {ID: "cb1mar", Name: "Sumber Sinergi"},
	"IPAC": {ID: "c2ip4c", Name: "ERA Graharealty"},
	"IPCC": {ID: "bgvlmw", Name: "IPCC"},
	"IPCM": {ID: "bkguec", Name: "Jasa Armada"},
	"IPOL": {ID: "bkguh7", Name: "Indopoly Swakars"},
	"IPTV": {ID: "bqrdim", Name: "MNC Vision"},
	"IRRA": {ID: "bs6n9c", Name: "Itama Ranoraya"},
	"IRSX": {ID: "c8ptdm", Name: "Aviana Sinar Aba"},
	"ISAP": {ID: "c87m5r", Name: "Isra Presisi"},
	"ISAT": {ID: "bn95p2", Name: "Indosat"},
	"ISEA": {ID: "cdmkyc", Name: "Indo American"},
	"ISSP": {ID: "bn95rw", Name: "Steel Pipe"},
	"ITIC": {ID: "bqptyc", Name: "Indonesian Tobac"},
	"ITMA": {ID: "bkgt9c", Name: "Sumber Energi"},
	"ITMG": {ID: "bn95ur", Name: "ITM"},
	"JARR": {ID: "c6yb2w", Name: "Jhonlin Agro Ray"},
	"JAST": {ID: "bpztur", Name: "Jasnita"},
	"JATI": {ID: "c9pikr", Name: "Informasi"},
	"JAWA": {ID: "bkgtf2", Name: "Jaya Agra Wattie"},
	"JAYA": {ID: "bp3fkr", Name: "Armada Berjaya"},
	"JECC": {ID: "bkgthw", Name: "Jembo Cable Co"},
	"JGLE": {ID: "bkgtkr", Name: "Graha"},
	"JIHD": {ID: "bkgtnm", Name: "Jakarta Intl"},
	"JKON": {ID: "bn95xm", Name: "Jaya Konstruksi"},
	"JMAS": {ID: "bkgwcw", Name: "Asuransi Jiwa"},
	"JPFA": {ID: "bkgwfr", Name: "Japfa Comfeed ID"},
	"JRPT": {ID: "bkgwim", Name: "Jaya Real Prpty"},
	"JSMR": {ID: "bn964c", Name: "Jasa Marga"},
	"JSPT": {ID: "bkgwr7", Name: "JKT Setiabudi"},
	"JTPE": {ID: "bkgwu2", Name: "Jasuindo Tiga"},
	"KAEF": {ID: "bkgvp2", Name: "Kimia Farma"},
	"KAQI": {ID: "cg3ah7", Name: "Jantra Grupo"},
	"KARW": {ID: "bkgvrw", Name: "Meratus Jasa"},
	"KBAG": {ID: "bu8obh", Name: "Karya Bersama"},
	"KBLI": {ID: "bkgvur", Name: "KMI Wire & Cable"},
	"KBLM": {ID: "bkgvxm", Name: "Kabelindo Murni"},
	"KBLV": {ID: "bkgw1h", Name: "First Media ID"},
	"KDSI": {ID: "bkgwww", Name: "Kedawung Indl"},
	"KDTN": {ID: "c7sxar", Name: "Puri Sentul"},
	"KEEN": {ID: "brdma2", Name: "Kencana Energi"},
	"KEJU": {ID: "bss8im", Name: "Mulia Boga Raya"},
	"KETR": {ID: "c7x3cw", Name: "Ketrosden"},
	"KIAS": {ID: "bgw8lh", Name: "Keramika ID"},
	"KICI": {ID: "bkgwzr", Name: "Kedaung Indah"},
	"KIJA": {ID: "bkgx3m", Name: "Jababeka"},
	"KING": {ID: "c8v3jc", Name: "Hoffmen Cleanind"},
	"KINO": {ID: "bkgx6h", Name: "Kino Indonesia"},
	"KIOS": {ID: "bkgx9c", Name: "Kioson Komersial"},
	"KJEN": {ID: "bqoa1h", Name: "Krida Jaringan"},
	"KKES": {ID: "c71dsm", Name: "Kusuma Kemindo"},
	"KKGI": {ID: "bkgxqh", Name: "Resource Alam ID"},
	"KLAS": {ID: "c9zg9c", Name: "Pelayaran Kurnia"},
	"KLBF": {ID: "bn96u2", Name: "Kalbe Farma"},
	"KLIN": {ID: "c71ear", Name: "Klinko Karya Ima"},
	"KMDS": {ID: "bvpjz2", Name: "KMDS"},
	"KMTR": {ID: "bkgxw7", Name: "Kirana Megatara"},
	"KOBX": {ID: "bkgxz2", Name: "Kobexindo"},
	"KOCI": {ID: "cazma2", Name: "Kokoh Exa"},
	"KOIN": {ID: "bkgy2w", Name: "Kokoh Inti"},
	"KOKA": {ID: "cb2m5r", Name: "Koka Indonesia"},
	"KONI": {ID: "bkgy5r", Name: "Perdana Bangun"},
	"KOPI": {ID: "bkgy8m", Name: "Mitra Energi"},
	"KOTA": {ID: "bqspm7", Name: "DMS Propertindo"},
	"KPIG": {ID: "bkgxf2", Name: "MNC Tourism Indo"},
	"KRAS": {ID: "bn96zr", Name: "Krakatau Steel"},
	"KREN": {ID: "bkgxnm", Name: "Quantum Clovera"},
	"KRYA": {ID: "c6vopr", Name: "Bangun Karya Per"},
	"KSIX": {ID: "cfl4f2", Name: "Kentanix Supra"},
	"KUAS": {ID: "c3tgqh", Name: "Ace Oldfields"},
	"LABA": {ID: "c2ekur", Name: "Green Power"},
	"LABS": {ID: "cdml7w", Name: "UBC Medical"},
	"LAJU": {ID: "c8ni2w", Name: "PT Jasa Berdikar"},
	"LAND": {ID: "bgwfxm", Name: "Trimitra"},
	"LAPD": {ID: "bkgybh", Name: "Leyand Intl"},
	"LCKM": {ID: "bkgyh7", Name: "LCK Global"},
	"LEAD": {ID: "bkgyk2", Name: "Logindo Samudra"},
	"LFLO": {ID: "c1g5f2", Name: "Imago Mulia"},
	"LIFE": {ID: "bqsrz2", Name: "MSIG Life Ins"},
	"LINK": {ID: "bkgymw", Name: "Link Net"},
	"LION": {ID: "bkgypr", Name: "Lion Metal Works"},
	"LIVE": {ID: "ccbz52", Name: "Homeco Victoria"},
	"LMAX": {ID: "caj9gh", Name: "Lupromax Pelumas"},
	"LMPI": {ID: "bkgyyc", Name: "Langgeng Makmur"},
	"LMSH": {ID: "bkgz27", Name: "Lionmesh Prima"},
	"LOPI": {ID: "cb2a2w", Name: "Logisticsplus"},
	"LPCK": {ID: "bkgz52", Name: "Lippo Cikarang"},
	"LPGI": {ID: "bkgz7w", Name: "Lippo Gen Insur"},
	"LPIN": {ID: "bkgzar", Name: "Multi Prima"},
	"LPKR": {ID: "bn99ar", Name: "Lippo Karawaci"},
	"LPLI": {ID: "bn99dm", Name: "Star Pacific"},
	"LPPF": {ID: "bkgzjc", Name: "Matahari Dept"},
	"LPPS": {ID: "bn99gh", Name: "Lenox Pasifik"},
	"LRNA": {ID: "bkgzp2", Name: "Eka Sari Lorena"},
	"LSIP": {ID: "bn99jc", Name: "PP Lonsum"},
	"LTLS": {ID: "bkgzur", Name: "Lautan Luas"},
	"LUCK": {ID: "bny8z2", Name: "Sentral Mitra In"},
	"LUCY": {ID: "c1zlh7", Name: "Lima Dua Lima"},
	"MAHA": {ID: "caem3m", Name: "Mandiri Herindo"},
	"MAIN": {ID: "bkh177", Name: "Malindo Feedmill"},
	"MANG": {ID: "cc463m", Name: "Manggung Polahra"},
	"MAPA": {ID: "bgwzm7", Name: "MAPA"},
	"MAPB": {ID: "bkh1cw", Name: "Map Boga Adiperk"},
	"MAPI": {ID: "bn98pr", Name: "Mitra Adiperkasa"},
	"MARI": {ID: "bkh1im", Name: "MARI"},
	"MARK": {ID: "bkh1lh", Name: "Mark Dynamics ID"},
	"MASB": {ID: "c2jw8m", Name: "Bank Multiarta"},
	"MAXI": {ID: "c9zd5r", Name: "Maxindo Karya"},
	"MAYA": {ID: "bkh1r7", Name: "Bank Mayapada"},
	"MBAP": {ID: "bkh1u2", Name: "Mitrabara"},
	"MBMA": {ID: "c9fe52", Name: "Merdeka Battery"},
	"MBSS": {ID: "bkh1ww", Name: "Mitrabahtera"},
	"MBTO": {ID: "bkh1zr", Name: "Martina Berto"},
	"MCAS": {ID: "bkh23m", Name: "M Cash Integrasi"},
	"MCOL": {ID: "c3apnm", Name: "Prima Andalan"},
	"MCOR": {ID: "bkh26h", Name: "CCB Indonesia"},
	"MDIA": {ID: "bkh2c7", Name: "Intermedia Cap"},
	"MDIY": {ID: "cff1lh", Name: "Daya Intiguna"},
	"MDKA": {ID: "bkh2f2", Name: "Merdeka Copper"},
	"MDKI": {ID: "bkh2hw", Name: "Emdeki Utama"},
	"MDLA": {ID: "cgbphw", Name: "Medela Potentia"},
	"MDLN": {ID: "bkh2kr", Name: "Modernland"},
	"MDRN": {ID: "bkh2nm", Name: "Modern Internasi"},
	"MEDC": {ID: "bn9a77", Name: "Medco Energi"},
	"MEDS": {ID: "c71idm", Name: "Hetzer Medical"},
	"MEGA": {ID: "bkh2tc", Name: "Bank Mega"},
	"MEJA": {ID: "ccbqh7", Name: "Pt Harta Djaya K"},
	"MENN": {ID: "c9fbu2", Name: "Menn"},
	"MERI": {ID: "che6cw", Name: "Merry Riana"},
	"MERK": {ID: "bkh2w7", Name: "Merck Indonesia"},
	"MFMI": {ID: "bkh35r", Name: "Multifiling"},
	"MGLV": {ID: "c2cba2", Name: "Panca Anugrah"},
	"MGNA": {ID: "bkh38m", Name: "Magna Investama"},
	"MGRO": {ID: "bgxdcw", Name: "Mahkota Group"},
	"MHKI": {ID: "ccwk27", Name: "Multi Hanna"},
	"MICE": {ID: "bn9afr", Name: "Multi Indocitra"},
	"MIDI": {ID: "bn9aim", Name: "Midi Utama ID"},
	"MIKA": {ID: "bkh3h7", Name: "Mitra Keluarga"},
	"MINA": {ID: "bkh427", Name: "Sanurhasta Mitra"},
	"MINE": {ID: "cg3epr", Name: "Sinar Terang"},
	"MIRA": {ID: "bkh452", Name: "Mitra Intl Rsrcs"},
	"MITI": {ID: "bkh47w", Name: "Mitra Investindo"},
	"MKAP": {ID: "ccbrar", Name: "Multikarya Asia"},
	"MKPI": {ID: "bkh4dm", Name: "Metropolitan ID"},
	"MKTR": {ID: "c7sz6h", Name: "MKTR"},
	"MLBI": {ID: "bkh4gh", Name: "Multi Bintang ID"},
	"MLIA": {ID: "bkh4jc", Name: "Mulia Industri"},
	"MLPL": {ID: "bn9alh", Name: "Multipolar"},
	"MLPT": {ID: "bkh4p2", Name: "Multipolar Tech"},
	"MMIX": {ID: "c87lz2", Name: "Multi Medika Int"},
	"MMLP": {ID: "bkh4rw", Name: "MMP"},
	"MNCN": {ID: "bkh4ur", Name: "Media Citra"},
	"MOLI": {ID: "b9fksm", Name: "Madusari Murni"},
	"MORA": {ID: "c6zya2", Name: "Moratelindo"},
	"MPIX": {ID: "ccbqmw", Name: "Mitra Pedagang"},
	"MPMX": {ID: "bkh3mw", Name: "Mitra Pinasthika"},
	"MPOW": {ID: "bkh3pr", Name: "MegaPower Makmur"},
	"MPPA": {ID: "bn9azr", Name: "Matahari Putra"},
	"MPRO": {ID: "bkh3vh", Name: "Maha Properti"},
	"MPXL": {ID: "c9ql7w", Name: "MPX Logistics"},
	"MRAT": {ID: "bkh3yc", Name: "Mustika Ratu"},
	"MREI": {ID: "bkhcur", Name: "Marein"},
	"MSIE": {ID: "cakqgh", Name: "Multisarana"},
	"MSIN": {ID: "bgy7nm", Name: "MNC Digital"},
	"MSJA": {ID: "cc466h", Name: "Multi Spunindo"},
	"MSKY": {ID: "bkhcxm", Name: "MNC Sky Vision"},
	"MSTI": {ID: "cbe9qh", Name: "Mastersys"},
	"MTDL": {ID: "bkhd1h", Name: "Metrodata Elec"},
	"MTEL": {ID: "c45acw", Name: "Mitratel"},
	"MTFN": {ID: "bgy82w", Name: "Capitalinc Inv"},
	"MTLA": {ID: "bkhd4c", Name: "MetLand"},
	"MTMH": {ID: "c5w4lh", Name: "Murni Sadar"},
	"MTPS": {ID: "bpmq9c", Name: "Meta Epsi"},
	"MTSM": {ID: "bkhda2", Name: "Metro Realty"},
	"MTWI": {ID: "bkhdfr", Name: "MTWI"},
	"MUTU": {ID: "cajgyc", Name: "Mutuagung"},
	"MYOH": {ID: "bkhcgh", Name: "Samindo Rsrcs"},
	"MYOR": {ID: "bn9bkr", Name: "Mayora Indah"},
	"MYTX": {ID: "bkhcp2", Name: "APAC Inv"},
	"NAIK": {ID: "cf6abh", Name: "Adiwarna Anugera"},
	"NANO": {ID: "c5es5r", Name: "Nanotech Indones"},
	"NASA": {ID: "bkhc52", Name: "Andalan Perkasa"},
	"NASI": {ID: "c4earw", Name: "Wahana Inti"},
	"NATO": {ID: "bor3r7", Name: "Surya Permata"},
	"NAYZ": {ID: "c8pvw7", Name: "Hassana Boga"},
	"NCKL": {ID: "c9dmnm", Name: "Trimegah Bangun"},
	"NELY": {ID: "bkhcar", Name: "Pelayaran Nelly"},
	"NEST": {ID: "cecdh7", Name: "Esta Indonesia"},
	"NETV": {ID: "c4zpnm", Name: "MDTV Media Tech"},
	"NFCX": {ID: "bh2cm7", Name: "NFC Indonesia"},
	"NICE": {ID: "cc46f2", Name: "Adhi Kartiko"},
	"NICK": {ID: "bkhdoc", Name: "Charnic Capital"},
	"NICL": {ID: "c2og3m", Name: "PAM Mineral"},
	"NIKL": {ID: "bkhdr7", Name: "Latinusa"},
	"NINE": {ID: "c87ih7", Name: "Techno9 Id Pt"},
	"NIRO": {ID: "bkhdww", Name: "City Retail Deve"},
	"NISP": {ID: "bkhdzr", Name: "Bank OCBC NISP"},
	"NOBU": {ID: "bkhe3m", Name: "Nobu Bank"},
	"NPGF": {ID: "c1mpp2", Name: "Nusa Palapa"},
	"NRCA": {ID: "bkhe9c", Name: "Nusa Raya Cipta"},
	"NSSS": {ID: "c92ssm", Name: "PT Nusantara"},
	"NTBK": {ID: "c53nim", Name: "Nusatama Berkah"},
	"NZIA": {ID: "brkv8m", Name: "Nusantara"},
	"OASA": {ID: "bkhdim", Name: "Maharaksa Biru"},
	"OBAT": {ID: "cflf77", Name: "Brigit Biofarmak"},
	"OBMD": {ID: "c4dnkr", Name: "OBM"},
	"OILS": {ID: "c3a84c", Name: "Indo Oil Perkasa"},
	"OKAS": {ID: "bkhdlh", Name: "Ancora ID Rscrs"},
	"OLIV": {ID: "c64i27", Name: "Oscar Mitra Suks"},
	"OMED": {ID: "c7t2jc", Name: "Jayamas Medica"},
	"OMRE": {ID: "bkhekr", Name: "Indo Prima Prpty"},
	"OPMS": {ID: "brkez2", Name: "Optima Prima"},
	"PACK": {ID: "c8sn2w", Name: "Abadi Nusantara"},
	"PADA": {ID: "c87qyc", Name: "Personel Alih"},
	"PADI": {ID: "bkheqh", Name: "Minna Padi"},
	"PALM": {ID: "bkhetc", Name: "Provident Invest"},
	"PAMG": {ID: "bqrcxm", Name: "Bima Sakti"},
	"PANI": {ID: "bh3952", Name: "Pratama Abadi"},
	"PANR": {ID: "bkhez2", Name: "Panorama Sentra"},
	"PANS": {ID: "bkhf2w", Name: "Panin Sekuritas"},
	"PART": {ID: "cdlta2", Name: "Cipta Perdana"},
	"PBID": {ID: "bkhf5r", Name: "Panca Budi"},
	"PBRX": {ID: "bkhf8m", Name: "Pan Brothers"},
	"PBSA": {ID: "bkhfbh", Name: "PBS"},
	"PCAR": {ID: "bkhfec", Name: "Prima Cakrawala"},
	"PDES": {ID: "bkhfh7", Name: "Destinasi Tirta"},
	"PDPP": {ID: "c7wzkr", Name: "Primadaya"},
	"PEGE": {ID: "bkhfk2", Name: "Panca Kapital"},
	"PEHA": {ID: "boeyr7", Name: "Phapros"},
	"PEVE": {ID: "c8lqu2", Name: "Penta Valent"},
	"PGAS": {ID: "bn9ch7", Name: "PGN"},
	"PGEO": {ID: "c8wmc7", Name: "Pertamina Enrgy"},
	"PGJO": {ID: "btf6im", Name: "Bahtera Bumi"},
	"PGLI": {ID: "bkhfpr", Name: "Graha Lestari"},
	"PGUN": {ID: "bv2tpr", Name: "Pradiksi"},
	"PICO": {ID: "bkhfvh", Name: "Pelangi Indah"},
	"PIPA": {ID: "c9cy5r", Name: "Multi Makmur"},
	"PJAA": {ID: "bkhfyc", Name: "Jaya Ancol"},
	"PKPK": {ID: "bkhh1h", Name: "Perdana Karya"},
	"PLAN": {ID: "bvsmnm", Name: "PPJ"},
	"PLIN": {ID: "bkhh77", Name: "Plaza ID Realty"},
	"PMJS": {ID: "bt81mw", Name: "Putra Mandiri"},
	"PMMP": {ID: "bx3rtc", Name: "Panca Mitra Mult"},
	"PMUI": {ID: "che6fr", Name: "Prima Multi"},
	"PNBN": {ID: "bn9d27", Name: "PaninBank"},
	"PNBS": {ID: "bn9d52", Name: "Bank Panin Dubai"},
	"PNGO": {ID: "bvilbh", Name: "Pinago Utama"},
	"PNIN": {ID: "bkhhfr", Name: "Paninvest"},
	"PNLF": {ID: "bn9d7w", Name: "Panin Financial"},
	"PNSE": {ID: "bkhhlh", Name: "Pudjiadi and Son"},
	"POLA": {ID: "bnw452", Name: "Pool Advista Fin"},
	"POLI": {ID: "bokeh7", Name: "Pollux Hotels"},
	"POLU": {ID: "bqiq5r", Name: "Golden Flower"},
	"POLY": {ID: "bkhg27", Name: "APAC Fibers"},
	"PORT": {ID: "bkhg7w", Name: "Nusantara"},
	"POWR": {ID: "bn9dar", Name: "Cikarang Lstndo"},
	"PPGL": {ID: "bv7ka2", Name: "Prima Globalindo"},
	"PPRE": {ID: "bkhgdm", Name: "PP Presisi"},
	"PPRI": {ID: "caj5xm", Name: "Paperocks"},
	"PPRO": {ID: "bkhggh", Name: "PP Properti"},
	"PRAY": {ID: "c7svf2", Name: "Famon Awal Bros"},
	"PRDA": {ID: "bkhgm7", Name: "Prodia Widyahusa"},
	"PRIM": {ID: "bh3bnm", Name: "Royal Prima"},
	"PSAB": {ID: "bkhgp2", Name: "J Resources Asia"},
	"PSDN": {ID: "bkhgrw", Name: "Prasidha Aneka"},
	"PSGO": {ID: "bssb7w", Name: "Palma Serasih"},
	"PSKT": {ID: "bkhgur", Name: "Red Planet"},
	"PSSI": {ID: "bkhgxm", Name: "IMC Pelita"},
	"PTBA": {ID: "bn9i4c", Name: "Bukit Asam"},
	"PTDU": {ID: "bwzbim", Name: "Djasa Ubersakti"},
	"PTIS": {ID: "bkhif2", Name: "Indo Straits"},
	"PTMP": {ID: "c8zh3m", Name: "Mitra Pack"},
	"PTMR": {ID: "cese7w", Name: "PT Master Print"},
	"PTPP": {ID: "bkhihw", Name: "PP (Persero)"},
	"PTPS": {ID: "cb26pr", Name: "Pulau Subur"},
	"PTPW": {ID: "btowc7", Name: "Pratama Widya"},
	"PTRO": {ID: "bkhinm", Name: "Petrosea"},
	"PTSN": {ID: "bkhiqh", Name: "Sat Nusapersada"},
	"PTSP": {ID: "bkhitc", Name: "Pioneerindo"},
	"PUDP": {ID: "bkhiw7", Name: "Pudjiadi Prestig"},
	"PURA": {ID: "btjqcw", Name: "Puratrans"},
	"PURI": {ID: "bvmvlh", Name: "Puri Glo Sukses"},
	"PWON": {ID: "bkhiz2", Name: "Pakuwon Jati"},
	"PYFA": {ID: "bkhj2w", Name: "Pyridam Farma"},
	"PZZA": {ID: "bh3dar", Name: "Sarimelati"},
	"RAAM": {ID: "c9pg7w", Name: "Tripar Multi"},
	"RAFI": {ID: "c6zy1h", Name: "Sari Kreasi Boga"},
	"RAJA": {ID: "bkhhu2", Name: "Rukun Raharja"},
	"RALS": {ID: "bn9iim", Name: "Ramayana Lestari"},
	"RANC": {ID: "bkhhzr", Name: "Supra Boga"},
	"RATU": {ID: "cfl3oc", Name: "Raharja Energi"},
	"RBMS": {ID: "bkhi3m", Name: "Ristia Bintang"},
	"RCCC": {ID: "c6y4ur", Name: "Utama Radar"},
	"RDTX": {ID: "bkhi6h", Name: "Roda Vivatex"},
	"REAL": {ID: "bsxdzr", Name: "Repower Asia"},
	"RELF": {ID: "ca43u2", Name: "Graha Mitra"},
	"RELI": {ID: "bkhi9c", Name: "Reliance Skrt ID"},
	"RGAS": {ID: "cbe25r", Name: "Kian Santang"},
	"RICY": {ID: "bkhj5r", Name: "Ricky Putra"},
	"RIGS": {ID: "bkhj8m", Name: "Rig Tenders ID"},
	"RISE": {ID: "bh3par", Name: "Jaya Sukses"},
	"RMKE": {ID: "c4bf52", Name: "RMK Energy"},
	"RMKO": {ID: "cafyoc", Name: "Royaltama Mulia"},
	"ROCK": {ID: "bvpnqh", Name: "Rockfields"},
	"RODA": {ID: "bkhkur", Name: "Pikko Land Dev"},
	"RONY": {ID: "bua477", Name: "Aracord"},
	"ROTI": {ID: "bkhkxm", Name: "Nippon Indosari"},
	"RSCH": {ID: "caoza2", Name: "Charlie Hospital"},
	"RSGK": {ID: "c3atf2", Name: "Kedoya Adyaraya"},
	"RUIS": {ID: "bkhjh7", Name: "Radiant Utama"},
	"RUNS": {ID: "c3athw", Name: "Global Sukses"},
	"SAFE": {ID: "bh4khw", Name: "Steady Safe"},
	"SAGE": {ID: "c8ztkr", Name: "Saptausaha Gemil"},
	"SAME": {ID: "bkhl1h", Name: "Sarana Meditama"},
	"SAMF": {ID: "bu77h7", Name: "Saraswanti"},
	"SAPX": {ID: "bkhl4c", Name: "Satria Antaran"},
	"SATU": {ID: "bnmpyc", Name: "Kota Satu"},
	"SBMA": {ID: "c3apw7", Name: "Surya Biru Murni"},
	"SCCO": {ID: "bkhl77", Name: "Sucaco"},
	"SCMA": {ID: "bkhla2", Name: "Surya Citra"},
	"SCNP": {ID: "bvpljc", Name: "SCNP"},
	"SDMU": {ID: "bkhlcw", Name: "Sidomulyo"},
	"SDPC": {ID: "bkhlfr", Name: "Millennium P Int"},
	"SDRA": {ID: "bkhlim", Name: "Bk Woori Saudara"},
	"SEMA": {ID: "c4s94c", Name: "Semacom"},
	"SFAN": {ID: "bqigoc", Name: "Surya Fajar Cap"},
	"SGER": {ID: "bvdqa2", Name: "SGE"},
	"SGRO": {ID: "bn9j9c", Name: "Prime Agri Rsrcs"},
	"SHID": {ID: "bkhlww", Name: "Hotel Sahid Jaya"},
	"SHIP": {ID: "bkhlzr", Name: "Sillo Maritime"},
	"SICO": {ID: "c5tatc", Name: "Sigma Energy"},
	"SIDO": {ID: "bkhm6h", Name: "Sido Muncul"},
	"SILO": {ID: "bn9jnm", Name: "Siloam Intl"},
	"SIMP": {ID: "bkhmf2", Name: "Salim Ivomas"},
	"SINI": {ID: "bsn27w", Name: "Singaraja Putra"},
	"SIPD": {ID: "bkhpzr", Name: "Sreeya Sewu Indo"},
	"SKBM": {ID: "bkhq3m", Name: "Sekar Bumi"},
	"SKLT": {ID: "bkhq6h", Name: "Sekar Laut"},
	"SKRN": {ID: "bkhqc7", Name: "Superkrane Mitra"},
	"SLIS": {ID: "bs6kh7", Name: "Gaya Abadi"},
	"SMAR": {ID: "bkhrmw", Name: "SMART ID"},
	"SMBR": {ID: "bn9lar", Name: "Semen Baturaja"},
	"SMCB": {ID: "bn9ldm", Name: "Solusi Bangun In"},
	"SMDM": {ID: "bkhryc", Name: "Suryamas Duta"},
	"SMDR": {ID: "bkhs27", Name: "Samudera ID"},
	"SMGA": {ID: "cc93tc", Name: "Sumber Mineral"},
	"SMGR": {ID: "bn9lgh", Name: "Semen Indonesia"},
	"SMIL": {ID: "c9r7oc", Name: "Sarana Mitra"},
	"SMKL": {ID: "bqrfh7", Name: "Satyamitra Kemas"},
	"SMKM": {ID: "c5gqk2", Name: "Sumber Mas"},
	"SMLE": {ID: "cc45oc", Name: "Sinergi Multi"},
	"SMMA": {ID: "bkhs7w", Name: "Sinar Mas Multi"},
	"SMMT": {ID: "bkhsar", Name: "Golden Eagle"},
	"SMRA": {ID: "bn9ljc", Name: "Summarecon Agung"},
	"SMSM": {ID: "bkhsjc", Name: "Selamat Sempurna"},
	"SNLK": {ID: "c1c3ur", Name: "Sunter Lakeside"},
	"SOCI": {ID: "bkhmkr", Name: "Soechi Lines"},
	"SOFA": {ID: "bv1prw", Name: "Solusi Envrmt"},
	"SOHO": {ID: "bvpia2", Name: "Soho Global Hlth"},
	"SOLA": {ID: "cd3j77", Name: "Xolare RCR"},
	"SONA": {ID: "bkhmqh", Name: "Sona Topas Tour"},
	"SOSS": {ID: "borblh", Name: "SOS"},
	"SOTS": {ID: "bo5fk2", Name: "SMK"},
	"SOUL": {ID: "c8hmu2", Name: "Mitra Tirta Buwa"},
	"SPMA": {ID: "bkhqhw", Name: "Suparma"},
	"SPRE": {ID: "cdllww", Name: "Soraya Berjaya"},
	"SPTO": {ID: "bh4tpr", Name: "Surya Pertiwi"},
	"SQMI": {ID: "bkhqkr", Name: "Renuka Coalindo"},
	"SRAJ": {ID: "bkhqnm", Name: "Sejahteraraya"},
	"SRSN": {ID: "bkhqw7", Name: "Indo Acidatama"},
	"SRTG": {ID: "bkhqz2", Name: "Saratoga Investa"},
	"SSIA": {ID: "bkhr2w", Name: "Surya Semesta"},
	"SSMS": {ID: "bkhr5r", Name: "Sawit Sumbermas"},
	"SSTM": {ID: "bkhr8m", Name: "Sunson Textile"},
	"STAA": {ID: "c5grjc", Name: "STA Resources"},
	"STAR": {ID: "bkhrbh", Name: "Buana Artha"},
	"STRK": {ID: "cb1rcw", Name: "Lovina Beach"},
	"STTP": {ID: "bkhrec", Name: "Siantar Top"},
	"SULI": {ID: "bn9l52", Name: "SLJ Global"},
	"SUNI": {ID: "c8irzr", Name: "Sunindo Pratama"},
	"SUPR": {ID: "bkhsp2", Name: "Solusi Tunas"},
	"SURE": {ID: "bkhsrw", Name: "Super Energy"},
	"SURI": {ID: "cbriz2", Name: "Maja Agung"},
	"SWAT": {ID: "bh4xyc", Name: "Sriwahana"},
	"SWID": {ID: "c6q9ww", Name: "Saraswanti"},
	"TALF": {ID: "bkhsxm", Name: "Tunas Alfin"},
	"TAMA": {ID: "btnwec", Name: "Lancartama"},
	"TAMU": {ID: "bkht1h", Name: "Pelayaran"},
	"TAPG": {ID: "c1pha2", Name: "Triputra Agro"},
	"TARA": {ID: "bkht4c", Name: "Agung Semesta"},
	"TAXI": {ID: "bkhta2", Name: "Express Trans ID"},
	"TAYS": {ID: "c4bfdm", Name: "Jaya Swarasa"},
	"TBIG": {ID: "bkhtcw", Name: "Tower Bersama"},
	"TBLA": {ID: "bn9m77", Name: "Tunas Baru"},
	"TBMS": {ID: "bkhtim", Name: "Tembaga Mulia"},
	"TCID": {ID: "bkhtlh", Name: "Mandom ID"},
	"TCPI": {ID: "bh55nm", Name: "Transcoal Pacifi"},
	"TEBE": {ID: "bsqufr", Name: "Dana Brata Luhur"},
	"TELE": {ID: "bkhtr7", Name: "Omni Inovasi"},
	"TFAS": {ID: "brgc52", Name: "Telefast"},
	"TFCO": {ID: "bkhtzr", Name: "Tifico Fiber ID"},
	"TGKA": {ID: "bkhu6h", Name: "Tigaraksa Satria"},
	"TGRA": {ID: "bkhu9c", Name: "Terregra Asia"},
	"TGUK": {ID: "ca99f2", Name: "Platinum Wahab"},
	"TIFA": {ID: "bkhuc7", Name: "KDB Tifa Finance"},
	"TINS": {ID: "bn9o2w", Name: "Timah"},
	"TIRA": {ID: "bkhunm", Name: "Tira Austenite"},
	"TIRT": {ID: "bkhuqh", Name: "Tirta Mahakam"},
	"TKIM": {ID: "bn9o5r", Name: "Tjiwi Kimia"},
	"TLDN": {ID: "c5tiqh", Name: "Teladan Prima"},
	"TLKM": {ID: "bn9o8m", Name: "Telkom Indonesia"},
	"TMAS": {ID: "bn9oec", Name: "Temas"},
	"TMPO": {ID: "bkhv8m", Name: "Tempo Inti Media"},
	"TNCA": {ID: "bh5cim", Name: "Trimuda Nuansa"},
	"TOBA": {ID: "bkhvk2", Name: "TBS Energi Utama"},
	"TOOL": {ID: "c71edm", Name: "Rohartindo"},
	"TOSK": {ID: "ccbqk2", Name: "Topindo Solusi"},
	"TOTL": {ID: "bn9ok2", Name: "Total Bangun"},
	"TOTO": {ID: "bkhvsm", Name: "Surya Toto ID"},
	"TOWR": {ID: "bn9omw", Name: "Sarana Menara"},
	"TPIA": {ID: "bkhvyc", Name: "Chandra"},
	"TPMA": {ID: "bkhw27", Name: "Trans Power"},
	"TRGU": {ID: "c6qatc", Name: "Cerestar ID"},
	"TRIM": {ID: "bki2lh", Name: "Trimegah Sekurit"},
	"TRIN": {ID: "btfcbh", Name: "Perintis Triniti"},
	"TRIS": {ID: "bki2oc", Name: "Trisula Intl"},
	"TRJA": {ID: "bviktc", Name: "Transkon Jaya"},
	"TRON": {ID: "c8zthw", Name: "Teknologi Karya"},
	"TRST": {ID: "bki2u2", Name: "Trias Sentosa"},
	"TRUE": {ID: "c2cfa2", Name: "Triniti Dinamik"},
	"TRUK": {ID: "bh7r6h", Name: "Guna Timur Raya"},
	"TRUS": {ID: "bki2zr", Name: "Trust Finance ID"},
	"TSPC": {ID: "bki33m", Name: "Tempo Scan ID"},
	"TUGU": {ID: "bh72cw", Name: "Asuransi Tugu"},
	"TYRE": {ID: "c9pfpr", Name: "King Tire"},
	"UANG": {ID: "bv1qlh", Name: "Pakuan"},
	"UCID": {ID: "bt7nnm", Name: "Uni-Charm"},
	"UDNG": {ID: "cbazxm", Name: "Agro Bahari Nusa"},
	"UFOE": {ID: "bxjur7", Name: "Damai Sejahtera"},
	"ULTJ": {ID: "bki36h", Name: "Ultrajaya Milk"},
	"UNIC": {ID: "bki39c", Name: "Unggul Indah"},
	"UNIQ": {ID: "bzv6mw", Name: "Ulima Nitra"},
	"UNSP": {ID: "bn9pjc", Name: "Bakrie Sumatera"},
	"UNTD": {ID: "ccanww", Name: "Terang Dunia Int"},
	"UNTR": {ID: "bn9pm7", Name: "United Tractors"},
	"UNVR": {ID: "bn9pp2", Name: "Unilever ID"},
	"URBN": {ID: "bo5fsm", Name: "Urban Jakarta"},
	"UVCR": {ID: "c2ruww", Name: "Trimegah Karya"},
	"VAST": {ID: "c8sn8m", Name: "Vastland Id Pt"},
	"VERN": {ID: "cesblh", Name: "Verona Indah"},
	"VICI": {ID: "bx3pp2", Name: "Victoria Care"},
	"VICO": {ID: "bki3nm", Name: "Victoria Investa"},
	"VINS": {ID: "bki3qh", Name: "Victoria Insur"},
	"VISI": {ID: "cchqzr", Name: "Satu Visi Putra"},
	"VIVA": {ID: "bki45r", Name: "Visi Media Asia"},
	"VKTR": {ID: "ca2e9c", Name: "VKTR"},
	"VOKS": {ID: "bki4bh", Name: "Voksel Electric"},
	"VRNA": {ID: "bki4k2", Name: "PT Mizuho Leasin"},
	"VTNY": {ID: "c89txm", Name: "Venteny Fortuna"},
	"WAPO": {ID: "bki4mw", Name: "Wahana Pronat"},
	"WEGE": {ID: "bki4pr", Name: "WIKA Gedung"},
	"WEHA": {ID: "bki4sm", Name: "WEHA Transportas"},
	"WGSH": {ID: "c4bevh", Name: "Wira Global"},
	"WICO": {ID: "bki76h", Name: "Wicaksana Intl"},
	"WIDI": {ID: "ca9dkr", Name: "PT Widiant Jaya"},
	"WIFI": {ID: "bx86dm", Name: "Solusi Sinergi"},
	"WIIM": {ID: "bki79c", Name: "Wismilak Inti"},
	"WIKA": {ID: "bn9q77", Name: "Wijaya Karya"},
	"WINE": {ID: "c8isf2", Name: "Hatten Bali"},
	"WINR": {ID: "c5yu77", Name: "Winner Nusantara"},
	"WINS": {ID: "bn9qa2", Name: "Wintermar Offshr"},
	"WIRG": {ID: "c5o9z2", Name: "Wir Asia"},
	"WMUU": {ID: "bxjkec", Name: "Widodo Makmur"},
	"WOMF": {ID: "bki7hw", Name: "WOM Finance"},
	"WOOD": {ID: "bki7kr", Name: "Integra Indocabi"},
	"WOWS": {ID: "bsnwf2", Name: "Ginting Jaya"},
	"WSBP": {ID: "bki7z2", Name: "Waskita Beton"},
	"WTON": {ID: "bn9r9c", Name: "WIKA Beton"},
	"YELO": {ID: "bnehec", Name: "Yelooo Integra"},
	"YOII": {ID: "cfl49c", Name: "Asuransi Digital"},
	"YPAS": {ID: "bki8bh", Name: "Yanaprima Hasta"},
	"YULE": {ID: "bki7nm", Name: "Yulie Sekuritas"},
	"YUPI": {ID: "cgaarw", Name: "Yupi Indo Jelly"},
	"ZATA": {ID: "c7x3im", Name: "Bersama Zatta Ja"},
	"ZBRA": {ID: "bhacdm", Name: "Dosni Roha"},
	"ZINC": {ID: "bki7qh", Name: "Kapuas Prima"},
	"ZONE": {ID: "bo5fyc", Name: "Mega Perintis"},
	"ZYRX": {ID: "c1c1kr", Name: "Zyrexindo Mandir"},
}

// IDXIDToTicker maps all MSN IDs (898) back to ticker symbols
// Some IDs may map to the same ticker (e.g., SOUL has multiple IDs)
var IDXIDToTicker = map[string]string{
	"cfatz2": "AADI",
	"bn8zk2": "AALI",
	"bkf9ec": "ABBA",
	"bkf9h7": "ABDA",
	"bkf9k2": "ABMM",
	"bn8zyc": "ACES",
	"cc48gh": "ACRO",
	"bkf9pr": "ACST",
	"c59mf2": "ADCP",
	"bkf9sm": "ADES",
	"bn9127": "ADHI",
	"bkf9yc": "ADMF",
	"bn9152": "ADMG",
	"c4pl52": "ADMR",
	"bn917w": "ADRO",
	"carobh": "AEGS",
	"bsu9xm": "AGAR",
	"bkfa7w": "AGII",
	"bkfaar": "AGRO",
	"bkfadm": "AGRS",
	"bkfagh": "AHAP",
	"bkfajc": "AIMS",
	"bkfam7": "AISA",
	"bkfctc": "AKKU",
	"bkfcw7": "AKPI",
	"bkfcz2": "AKRA",
	"bkfd2w": "AKSI",
	"bkfd5r": "ALDO",
	"ccanzr": "ALII",
	"bkfd8m": "ALKA",
	"bkfdbh": "ALMI",
	"bkfdec": "ALTO",
	"bkfchw": "AMAG",
	"btysar": "AMAN",
	"btf6a2": "AMAR",
	"bkfckr": "AMFG",
	"bkfcnm": "AMIN",
	"ca993m": "AMMN",
	"c6yaw7": "AMMS",
	"btfbw7": "AMOR",
	"bkfcqh": "AMRT",
	"bgrwf2": "ANDI",
	"bkfem7": "ANJT",
	"bn8zmw": "ANTM",
	"bkferw": "APEX",
	"bkfeur": "APIC",
	"bkfexm": "APII",
	"bkff1h": "APLI",
	"bkff4c": "APLN",
	"c2il1h": "ARCI",
	"ccsom7": "AREA",
	"bkff77": "ARGO",
	"bkffa2": "ARII",
	"bqtwtc": "ARKA",
	"c6qaqh": "ARKO",
	"bkfffr": "ARNA",
	"bkffim": "ARTA",
	"bkffoc": "ARTO",
	"bkffzr": "ASBI",
	"bkfg3m": "ASDM",
	"bkfg6h": "ASGR",
	"c6a3yc": "ASHA",
	"bn91gh": "ASII",
	"bkfgc7": "ASJT",
	"c4xl52": "ASLC",
	"cc41ww": "ASLI",
	"bkfgf2": "ASMI",
	"btr8pr": "ASPI",
	"chbyjc": "ASPR",
	"bkfghw": "ASRI",
	"bkfgkr": "ASRM",
	"bkfgnm": "ASSA",
	"bwzup2": "ATAP",
	"bkffr7": "ATIC",
	"ccwjvh": "ATLA",
	"bkffu2": "AUTO",
	"c4bepr": "AVIA",
	"c9f9yc": "AWAN",
	"c6v4pr": "AXIO",
	"cbkfkr": "AYAM",
	"btox8m": "AYLS",
	"bkfgqh": "BABP",
	"carnqh": "BABY",
	"bkfgtc": "BACA",
	"ccbzar": "BAIK",
	"bkfgw7": "BAJA",
	"bkfgz2": "BALI",
	"bxjrc7": "BANK",
	"bkfh2w": "BAPA",
	"breeur": "BAPI",
	"bkflyc": "BATA",
	"cddzvh": "BATR",
	"c4xpm7": "BAUT",
	"bkfm27": "BAYU",
	"bn91jc": "BBCA",
	"bkfm7w": "BBHI",
	"bkfmar": "BBKP",
	"bkfmdm": "BBLD",
	"bkfmgh": "BBMD",
	"bn91m7": "BBNI",
	"bn91p2": "BBRI",
	"bkfmrw": "BBRM",
	"bvpgvh": "BBSI",
	"bu9cqh": "BBSS",
	"bkfmur": "BBTN",
	"bkfmxm": "BBYB",
	"bkfn1h": "BCAP",
	"bgt4rw": "BCIC",
	"bkfn4c": "BCIP",
	"c8zmyc": "BDKR",
	"bn91rw": "BDMN",
	"bzv7ar": "BEBS",
	"bokavh": "BEEF",
	"c8if77": "BEER",
	"bkfna2": "BEKS",
	"c7svnm": "BELI",
	"bkfncw": "BELL",
	"btyakr": "BESS",
	"bkfh5r": "BEST",
	"bkfh8m": "BFIN",
	"bkfhbh": "BGTG",
	"bua6k2": "BHAT",
	"bkfhec": "BHIT",
	"c5iucw": "BIKE",
	"bkfkz2": "BIMA",
	"bn92u2": "BINA",
	"c45tp2": "BINO",
	"bn92ww": "BIPI",
	"bkfl8m": "BIPP",
	"bkflbh": "BIRD",
	"bn92zr": "BISI",
	"bkflh7": "BJBR",
	"bn936h": "BJTM",
	"bkflmw": "BKDP",
	"bkflpr": "BKSL",
	"bkflsm": "BKSW",
	"cdlvh7": "BLES",
	"chc7m7": "BLOG",
	"bgt5u2": "BLTA",
	"bkflvh": "BLTZ",
	"bqrgar": "BLUE",
	"bkfoqh": "BMAS",
	"c8isqh": "BMBL",
	"c2md4c": "BMHS",
	"bn939c": "BMRI",
	"bkfow7": "BMSR",
	"bkfoz2": "BMTR",
	"bkfp2w": "BNBA",
	"bn93c7": "BNBR",
	"bkfp8m": "BNGA",
	"bn93f2": "BNII",
	"bn93hw": "BNLI",
	"cf4yu2": "BOAT",
	"c3wioc": "BOBA",
	"bkfph7": "BOGA",
	"bqe3p2": "BOLA",
	"bkfpk2": "BOLT",
	"bkfppr": "BPFI",
	"bkfpsm": "BPII",
	"bgth1h": "BPTR",
	"bkfpvh": "BRAM",
	"cb1ra2": "BREN",
	"bgtha2": "BRIS",
	"bn924c": "BRMS",
	"bkfq27": "BRNA",
	"bn9277": "BRPT",
	"cflfa2": "BRRC",
	"c7svhw": "BSBK",
	"bkfq7w": "BSDE",
	"bn92a2": "BSIM",
	"c4is3m": "BSML",
	"bkfqdm": "BSSR",
	"bkfqgh": "BSWD",
	"bkfqjc": "BTEK",
	"bkfqp2": "BTON",
	"bkfqrw": "BTPN",
	"bgtwjc": "BTPS",
	"c71dyc": "BUAH",
	"bkfqur": "BUDI",
	"c2wgkr": "BUKA",
	"bkfqxm": "BUKK",
	"bkfnu2": "BULL",
	"bn92fr": "BUMI",
	"bkfnzr": "BUVA",
	"bkfo3m": "BVIC",
	"bn92im": "BWPT",
	"bn92lh": "BYAN",
	"bne4c7": "CAKK",
	"bkfoc7": "CAMP",
	"bkfof2": "CANI",
	"btysdm": "CARE",
	"bkfohw": "CARS",
	"bkfokr": "CASA",
	"bufc7w": "CASH",
	"bkfonm": "CASS",
	"cflejc": "CBDK",
	"c8ipmw": "CBPE",
	"c8ifww": "CBRE",
	"c7sxgh": "CBUT",
	"bqh6ar": "CCSI",
	"chdaw7": "CDIA",
	"bkfkqh": "CEKA",
	"bkfktc": "CENT",
	"bkfkw7": "CFIN",
	"cc45zr": "CGAS",
	"chddzr": "CHEK",
	"c6qahw": "CHEM",
	"c8qlmw": "CHIP",
	"bkfnfr": "CINT",
	"bkfnim": "CITA",
	"bjs6w7": "CITY",
	"bona52": "CLAY",
	"bkfnoc": "CLEO",
	"bkfnr7": "CLPI",
	"bn93kr": "CMNP",
	"c3bxcw": "CMNT",
	"bkgku2": "CMPP",
	"c4b81h": "CMRY",
	"bkgkzr": "CNKO",
	"cagkkr": "CNMA",
	"c78lp2": "COAL",
	"bpfy1h": "COCO",
	"chc7p2": "COIN",
	"bn93nm": "CPIN",
	"bkgl9c": "CPRO",
	"c71ep2": "CRAB",
	"ca9dnm": "CRSN",
	"bn93z2": "CSAP",
	"bkglf2": "CSIS",
	"bua4a2": "CSMI",
	"btf6cw": "CSRA",
	"bkglhw": "CTBN",
	"bn942w": "CTRA",
	"bkglnm": "CTTH",
	"c8ztf2": "CUAN",
	"caj9jc": "CYBR",
	"cf3dr7": "DAAZ",
	"btov1h": "DADA",
	"bkglqh": "DART",
	"cd3e27": "DATA",
	"bkgltc": "DAYA",
	"bxbr3m": "DCII",
	"bkglw7": "DEFI",
	"c461k2": "DEPO",
	"bn93qh": "DEWA",
	"c6t4oc": "DEWI",
	"bkgm2w": "DFAM",
	"bkgm5r": "DGIK",
	"bxbs2w": "DGNS",
	"cfl46h": "DGWG",
	"bguqr7": "DIGI",
	"bn93tc": "DILD",
	"bny8f2": "DIVA",
	"bkgmbh": "DKFT",
	"cgo8rw": "DKHH",
	"bkgn52": "DLTA",
	"bkgn7w": "DMAS",
	"bsh6z2": "DMMX",
	"bti2qh": "DMND",
	"bkgnar": "DNAR",
	"bkgndm": "DNET",
	"bkgngh": "DOID",
	"c9pg52": "DOOH",
	"cecd8m": "DOSS",
	"bkgnjc": "DPNS",
	"bkgnm7": "DPUM",
	"c4is9c": "DRMA",
	"bkgnp2": "DSFI",
	"bkgnrw": "DSNG",
	"bn94ec": "DSSA",
	"bn94h7": "DUTI",
	"bkgmsm": "DVLA",
	"bkgmvh": "DWGL",
	"bkgmyc": "DYAN",
	"bqrjmw": "EAST",
	"bkgn27": "ECII",
	"bxmmkr": "EDGE",
	"bkgmec": "EKAD",
	"c8ifcw": "ELIT",
	"c71dh7": "ELPI",
	"bkgmh7": "ELSA",
	"bn94k2": "ELTY",
	"ci4x5r": "EMAS",
	"bkgo77": "EMDE",
	"bkgocw": "EMTK",
	"c53nww": "ENAK",
	"bkgofr": "ENRG",
	"bvqna2": "ENZO",
	"buzekr": "EPAC",
	"bkgoim": "EPMT",
	"bkgolh": "ERAA",
	"cakb4c": "ERAL",
	"bkgooc": "ERTX",
	"bsq1dm": "ESIP",
	"bkgnxm": "ESSA",
	"btxltc": "ESTA",
	"bkgo1h": "ESTI",
	"c6zylh": "EURO",
	"bn94pr": "EXCL",
	"bx7mww": "FAPA",
	"bkgor7": "FAST",
	"bkgou2": "FASW",
	"bgva7w": "FILM",
	"c1paqh": "FIMP",
	"bkgozr": "FIRE",
	"bkgp3m": "FISH",
	"bqcw2w": "FITT",
	"c2p22w": "FLMC",
	"bkgp9c": "FMII",
	"caj9ar": "FOLK",
	"bohgur": "FOOD",
	"cghp7w": "FORE",
	"bkgpc7": "FORU",
	"bkgphw": "FPNI",
	"bqrhww": "FUJI",
	"c8xc2w": "FUTR",
	"c8no4c": "FWCT",
	"bkgpnm": "GDST",
	"bkgpqh": "GDYR",
	"bkgptc": "GEMA",
	"bkgpw7": "GEMS",
	"bn94vh": "GGRM",
	"brivww": "GGRP",
	"bkgq2w": "GHON",
	"bkgq5r": "GIAA",
	"bn9527": "GJTL",
	"bgveur": "GLOB",
	"bt94fr": "GLVA",
	"bkgqbh": "GMFI",
	"bkgqk2": "GMTD",
	"bkgqmw": "GOLD",
	"cdml52": "GOLF",
	"bkgqsm": "GOOD",
	"c5tv8m": "GOTO",
	"bkgqvh": "GPRA",
	"c39qp2": "GPSO",
	"cakam7": "GRIA",
	"cc65vh": "GRPH",
	"ca9bar": "GRPM",
	"bkgqec": "GSMF",
	"bkgqh7": "GTBO",
	"c9a7c7": "GTRA",
	"c3atkr": "GTSI",
	"c6ybbh": "GULA",
	"cdm6oc": "GUNA",
	"bkgqyc": "GWSA",
	"bkgr27": "GZCO",
	"bkgr52": "HADE",
	"c3839c": "HAIS",
	"c9c9z2": "HAJJ",
	"c8snbh": "HALO",
	"c6vxxm": "HATM",
	"caj5ur": "HBAT",
	"bkgr7w": "HDFA",
	"bqsr9c": "HDIT",
	"bgvigh": "HEAL",
	"bkgrdm": "HELI",
	"bkgrgh": "HERO",
	"bn95ar": "HEXA",
	"cfl3r7": "HGII",
	"c8xfhw": "HILL",
	"bkgrm7": "HITS",
	"bn95jc": "HMSP",
	"bkgrur": "HOKI",
	"bvpl7w": "HOMI",
	"c24y52": "HOPE",
	"bpplhw": "HRME",
	"bkgs4c": "HRTA",
	"bn957w": "HRUM",
	"caj9p2": "HUMI",
	"ccbzjc": "HYGN",
	"bkgsa2": "IATA",
	"bkgscw": "IBFN",
	"c5z1vh": "IBOS",
	"bkgsfr": "IBST",
	"bkgsim": "ICBP",
	"bkgslh": "ICON",
	"c3at9c": "IDEA",
	"bkgsoc": "IDPR",
	"bt26w7": "IFII",
	"bsua4c": "IFSH",
	"bkgsr7": "IGAR",
	"bkgsww": "IKAI",
	"btov4c": "IKAN",
	"bkgszr": "IKBI",
	"cbetnm": "IKPM",
	"bkguk2": "IMAS",
	"bkgumw": "IMJS",
	"bkgupr": "IMPC",
	"bkguvh": "INAI",
	"bkguyc": "INCF",
	"bkgv27": "INCI",
	"bn96cw": "INCO",
	"bn96fr": "INDF",
	"btf6ww": "INDO",
	"bkgvar": "INDR",
	"bkgvdm": "INDS",
	"bkgvgh": "INDX",
	"bkgvjc": "INDY",
	"caehu2": "INET",
	"bn96im": "INKP",
	"bqtw6h": "INOV",
	"bkgttc": "INPC",
	"bkgtw7": "INPP",
	"bkgtz2": "INPS",
	"bkgu2w": "INRU",
	"bkgu5r": "INTA",
	"bkgu8m": "INTD",
	"bn95m7": "INTP",
	"cb1mar": "IOTF",
	"c2ip4c": "IPAC",
	"bgvlmw": "IPCC",
	"bkguec": "IPCM",
	"bkguh7": "IPOL",
	"bqrdim": "IPTV",
	"bs6n9c": "IRRA",
	"c8ptdm": "IRSX",
	"c87m5r": "ISAP",
	"bn95p2": "ISAT",
	"cdmkyc": "ISEA",
	"bn95rw": "ISSP",
	"bqptyc": "ITIC",
	"bkgt9c": "ITMA",
	"bn95ur": "ITMG",
	"c6yb2w": "JARR",
	"bpztur": "JAST",
	"c9pikr": "JATI",
	"bkgtf2": "JAWA",
	"bp3fkr": "JAYA",
	"bkgthw": "JECC",
	"bkgtkr": "JGLE",
	"bkgtnm": "JIHD",
	"bn95xm": "JKON",
	"bkgwcw": "JMAS",
	"bkgwfr": "JPFA",
	"bkgwim": "JRPT",
	"bn964c": "JSMR",
	"bkgwr7": "JSPT",
	"bkgwu2": "JTPE",
	"bkgvp2": "KAEF",
	"cg3ah7": "KAQI",
	"bkgvrw": "KARW",
	"bu8obh": "KBAG",
	"bkgvur": "KBLI",
	"bkgvxm": "KBLM",
	"bkgw1h": "KBLV",
	"bkgwww": "KDSI",
	"c7sxar": "KDTN",
	"brdma2": "KEEN",
	"bss8im": "KEJU",
	"c7x3cw": "KETR",
	"bgw8lh": "KIAS",
	"bkgwzr": "KICI",
	"bkgx3m": "KIJA",
	"c8v3jc": "KING",
	"bkgx6h": "KINO",
	"bkgx9c": "KIOS",
	"bqoa1h": "KJEN",
	"c71dsm": "KKES",
	"bkgxqh": "KKGI",
	"c9zg9c": "KLAS",
	"bn96u2": "KLBF",
	"c71ear": "KLIN",
	"bvpjz2": "KMDS",
	"bkgxw7": "KMTR",
	"bkgxz2": "KOBX",
	"cazma2": "KOCI",
	"bkgy2w": "KOIN",
	"cb2m5r": "KOKA",
	"bkgy5r": "KONI",
	"bkgy8m": "KOPI",
	"bqspm7": "KOTA",
	"bkgxf2": "KPIG",
	"bn96zr": "KRAS",
	"bkgxnm": "KREN",
	"c6vopr": "KRYA",
	"cfl4f2": "KSIX",
	"c3tgqh": "KUAS",
	"c2ekur": "LABA",
	"cdml7w": "LABS",
	"c8ni2w": "LAJU",
	"bgwfxm": "LAND",
	"bkgybh": "LAPD",
	"bkgyh7": "LCKM",
	"bkgyk2": "LEAD",
	"c1g5f2": "LFLO",
	"bqsrz2": "LIFE",
	"bkgymw": "LINK",
	"bkgypr": "LION",
	"ccbz52": "LIVE",
	"caj9gh": "LMAX",
	"bkgyyc": "LMPI",
	"bkgz27": "LMSH",
	"cb2a2w": "LOPI",
	"bkgz52": "LPCK",
	"bkgz7w": "LPGI",
	"bkgzar": "LPIN",
	"bn99ar": "LPKR",
	"bn99dm": "LPLI",
	"bkgzjc": "LPPF",
	"bn99gh": "LPPS",
	"bkgzp2": "LRNA",
	"bn99jc": "LSIP",
	"bkgzur": "LTLS",
	"bny8z2": "LUCK",
	"c1zlh7": "LUCY",
	"caem3m": "MAHA",
	"bkh177": "MAIN",
	"cc463m": "MANG",
	"bgwzm7": "MAPA",
	"bkh1cw": "MAPB",
	"bn98pr": "MAPI",
	"bkh1im": "MARI",
	"bkh1lh": "MARK",
	"c2jw8m": "MASB",
	"c9zd5r": "MAXI",
	"bkh1r7": "MAYA",
	"bkh1u2": "MBAP",
	"c9fe52": "MBMA",
	"bkh1ww": "MBSS",
	"bkh1zr": "MBTO",
	"bkh23m": "MCAS",
	"c3apnm": "MCOL",
	"bkh26h": "MCOR",
	"bkh2c7": "MDIA",
	"cff1lh": "MDIY",
	"bkh2f2": "MDKA",
	"bkh2hw": "MDKI",
	"cgbphw": "MDLA",
	"bkh2kr": "MDLN",
	"bkh2nm": "MDRN",
	"bn9a77": "MEDC",
	"c71idm": "MEDS",
	"bkh2tc": "MEGA",
	"ccbqh7": "MEJA",
	"c9fbu2": "MENN",
	"che6cw": "MERI",
	"bkh2w7": "MERK",
	"bkh35r": "MFMI",
	"c2cba2": "MGLV",
	"bkh38m": "MGNA",
	"bgxdcw": "MGRO",
	"ccwk27": "MHKI",
	"bn9afr": "MICE",
	"bn9aim": "MIDI",
	"bkh3h7": "MIKA",
	"bkh427": "MINA",
	"cg3epr": "MINE",
	"bkh452": "MIRA",
	"bkh47w": "MITI",
	"ccbrar": "MKAP",
	"bkh4dm": "MKPI",
	"c7sz6h": "MKTR",
	"bkh4gh": "MLBI",
	"bkh4jc": "MLIA",
	"bn9alh": "MLPL",
	"bkh4p2": "MLPT",
	"c87lz2": "MMIX",
	"bkh4rw": "MMLP",
	"bkh4ur": "MNCN",
	"b9fksm": "MOLI",
	"c6zya2": "MORA",
	"ccbqmw": "MPIX",
	"bkh3mw": "MPMX",
	"bkh3pr": "MPOW",
	"bn9azr": "MPPA",
	"bkh3vh": "MPRO",
	"c9ql7w": "MPXL",
	"bkh3yc": "MRAT",
	"bkhcur": "MREI",
	"cakqgh": "MSIE",
	"bgy7nm": "MSIN",
	"cc466h": "MSJA",
	"bkhcxm": "MSKY",
	"cbe9qh": "MSTI",
	"bkhd1h": "MTDL",
	"c45acw": "MTEL",
	"bgy82w": "MTFN",
	"bkhd4c": "MTLA",
	"c5w4lh": "MTMH",
	"bpmq9c": "MTPS",
	"bkhda2": "MTSM",
	"bkhdfr": "MTWI",
	"cajgyc": "MUTU",
	"bkhcgh": "MYOH",
	"bn9bkr": "MYOR",
	"bkhcp2": "MYTX",
	"cf6abh": "NAIK",
	"c5es5r": "NANO",
	"bkhc52": "NASA",
	"c4earw": "NASI",
	"bor3r7": "NATO",
	"c8pvw7": "NAYZ",
	"c9dmnm": "NCKL",
	"bkhcar": "NELY",
	"cecdh7": "NEST",
	"c4zpnm": "NETV",
	"bh2cm7": "NFCX",
	"cc46f2": "NICE",
	"bkhdoc": "NICK",
	"c2og3m": "NICL",
	"bkhdr7": "NIKL",
	"c87ih7": "NINE",
	"bkhdww": "NIRO",
	"bkhdzr": "NISP",
	"bkhe3m": "NOBU",
	"c1mpp2": "NPGF",
	"bkhe9c": "NRCA",
	"c92ssm": "NSSS",
	"c53nim": "NTBK",
	"brkv8m": "NZIA",
	"bkhdim": "OASA",
	"cflf77": "OBAT",
	"c4dnkr": "OBMD",
	"c3a84c": "OILS",
	"bkhdlh": "OKAS",
	"c64i27": "OLIV",
	"c7t2jc": "OMED",
	"bkhekr": "OMRE",
	"brkez2": "OPMS",
	"c8sn2w": "PACK",
	"c87qyc": "PADA",
	"bkheqh": "PADI",
	"bkhetc": "PALM",
	"bqrcxm": "PAMG",
	"bh3952": "PANI",
	"bkhez2": "PANR",
	"bkhf2w": "PANS",
	"cdlta2": "PART",
	"bkhf5r": "PBID",
	"bkhf8m": "PBRX",
	"bkhfbh": "PBSA",
	"bkhfec": "PCAR",
	"bkhfh7": "PDES",
	"c7wzkr": "PDPP",
	"bkhfk2": "PEGE",
	"boeyr7": "PEHA",
	"c8lqu2": "PEVE",
	"bn9ch7": "PGAS",
	"c8wmc7": "PGEO",
	"btf6im": "PGJO",
	"bkhfpr": "PGLI",
	"bv2tpr": "PGUN",
	"bkhfvh": "PICO",
	"c9cy5r": "PIPA",
	"bkhfyc": "PJAA",
	"bkhh1h": "PKPK",
	"bvsmnm": "PLAN",
	"bkhh77": "PLIN",
	"bt81mw": "PMJS",
	"bx3rtc": "PMMP",
	"che6fr": "PMUI",
	"bn9d27": "PNBN",
	"bn9d52": "PNBS",
	"bvilbh": "PNGO",
	"bkhhfr": "PNIN",
	"bn9d7w": "PNLF",
	"bkhhlh": "PNSE",
	"bnw452": "POLA",
	"bokeh7": "POLI",
	"bqiq5r": "POLU",
	"bkhg27": "POLY",
	"bkhg7w": "PORT",
	"bn9dar": "POWR",
	"bv7ka2": "PPGL",
	"bkhgdm": "PPRE",
	"caj5xm": "PPRI",
	"bkhggh": "PPRO",
	"c7svf2": "PRAY",
	"bkhgm7": "PRDA",
	"bh3bnm": "PRIM",
	"bkhgp2": "PSAB",
	"bkhgrw": "PSDN",
	"bssb7w": "PSGO",
	"bkhgur": "PSKT",
	"bkhgxm": "PSSI",
	"bn9i4c": "PTBA",
	"bwzbim": "PTDU",
	"bkhif2": "PTIS",
	"c8zh3m": "PTMP",
	"cese7w": "PTMR",
	"bkhihw": "PTPP",
	"cb26pr": "PTPS",
	"btowc7": "PTPW",
	"bkhinm": "PTRO",
	"bkhiqh": "PTSN",
	"bkhitc": "PTSP",
	"bkhiw7": "PUDP",
	"btjqcw": "PURA",
	"bvmvlh": "PURI",
	"bkhiz2": "PWON",
	"bkhj2w": "PYFA",
	"bh3dar": "PZZA",
	"c9pg7w": "RAAM",
	"c6zy1h": "RAFI",
	"bkhhu2": "RAJA",
	"bn9iim": "RALS",
	"bkhhzr": "RANC",
	"cfl3oc": "RATU",
	"bkhi3m": "RBMS",
	"c6y4ur": "RCCC",
	"bkhi6h": "RDTX",
	"bsxdzr": "REAL",
	"ca43u2": "RELF",
	"bkhi9c": "RELI",
	"cbe25r": "RGAS",
	"bkhj5r": "RICY",
	"bkhj8m": "RIGS",
	"bh3par": "RISE",
	"c4bf52": "RMKE",
	"cafyoc": "RMKO",
	"bvpnqh": "ROCK",
	"bkhkur": "RODA",
	"bua477": "RONY",
	"bkhkxm": "ROTI",
	"caoza2": "RSCH",
	"c3atf2": "RSGK",
	"bkhjh7": "RUIS",
	"c3athw": "RUNS",
	"bh4khw": "SAFE",
	"c8ztkr": "SAGE",
	"bkhl1h": "SAME",
	"bu77h7": "SAMF",
	"bkhl4c": "SAPX",
	"bnmpyc": "SATU",
	"c3apw7": "SBMA",
	"bkhl77": "SCCO",
	"bkhla2": "SCMA",
	"bvpljc": "SCNP",
	"bkhlcw": "SDMU",
	"bkhlfr": "SDPC",
	"bkhlim": "SDRA",
	"c4s94c": "SEMA",
	"bqigoc": "SFAN",
	"bvdqa2": "SGER",
	"bn9j9c": "SGRO",
	"bkhlww": "SHID",
	"bkhlzr": "SHIP",
	"c5tatc": "SICO",
	"bkhm6h": "SIDO",
	"bn9jnm": "SILO",
	"bkhmf2": "SIMP",
	"bsn27w": "SINI",
	"bkhpzr": "SIPD",
	"bkhq3m": "SKBM",
	"bkhq6h": "SKLT",
	"bkhqc7": "SKRN",
	"bs6kh7": "SLIS",
	"bkhrmw": "SMAR",
	"bn9lar": "SMBR",
	"bn9ldm": "SMCB",
	"bkhryc": "SMDM",
	"bkhs27": "SMDR",
	"cc93tc": "SMGA",
	"bn9lgh": "SMGR",
	"c9r7oc": "SMIL",
	"bqrfh7": "SMKL",
	"c5gqk2": "SMKM",
	"cc45oc": "SMLE",
	"bkhs7w": "SMMA",
	"bkhsar": "SMMT",
	"bn9ljc": "SMRA",
	"bkhsjc": "SMSM",
	"c1c3ur": "SNLK",
	"bkhmkr": "SOCI",
	"bv1prw": "SOFA",
	"bvpia2": "SOHO",
	"cd3j77": "SOLA",
	"bkhmqh": "SONA",
	"borblh": "SOSS",
	"bo5fk2": "SOTS",
	"c8hmu2": "SOUL",
	"c8hmww": "SOUL",
	"c8hmzr": "SOUL",
	"bkhqhw": "SPMA",
	"cdllww": "SPRE",
	"bh4tpr": "SPTO",
	"bkhqkr": "SQMI",
	"bkhqnm": "SRAJ",
	"bkhqw7": "SRSN",
	"bkhqz2": "SRTG",
	"bkhr2w": "SSIA",
	"bkhr5r": "SSMS",
	"bkhr8m": "SSTM",
	"c5grjc": "STAA",
	"bkhrbh": "STAR",
	"cb1rcw": "STRK",
	"bkhrec": "STTP",
	"bn9l52": "SULI",
	"c8irzr": "SUNI",
	"bkhsp2": "SUPR",
	"bkhsrw": "SURE",
	"cbriz2": "SURI",
	"bh4xyc": "SWAT",
	"c6q9ww": "SWID",
	"bkhsxm": "TALF",
	"btnwec": "TAMA",
	"bkht1h": "TAMU",
	"c1pha2": "TAPG",
	"bkht4c": "TARA",
	"bkhta2": "TAXI",
	"c4bfdm": "TAYS",
	"bkhtcw": "TBIG",
	"bn9m77": "TBLA",
	"bkhtim": "TBMS",
	"bkhtlh": "TCID",
	"bh55nm": "TCPI",
	"bsqufr": "TEBE",
	"bkhtr7": "TELE",
	"brgc52": "TFAS",
	"bkhtzr": "TFCO",
	"bkhu6h": "TGKA",
	"bkhu9c": "TGRA",
	"ca99f2": "TGUK",
	"bkhuc7": "TIFA",
	"bn9o2w": "TINS",
	"bkhunm": "TIRA",
	"bkhuqh": "TIRT",
	"bn9o5r": "TKIM",
	"c5tiqh": "TLDN",
	"bn9o8m": "TLKM",
	"bn9oec": "TMAS",
	"bkhv8m": "TMPO",
	"bh5cim": "TNCA",
	"bkhvk2": "TOBA",
	"c71edm": "TOOL",
	"ccbqk2": "TOSK",
	"bn9ok2": "TOTL",
	"bkhvsm": "TOTO",
	"bn9omw": "TOWR",
	"bkhvyc": "TPIA",
	"bkhw27": "TPMA",
	"c6qatc": "TRGU",
	"bki2lh": "TRIM",
	"btfcbh": "TRIN",
	"bki2oc": "TRIS",
	"bviktc": "TRJA",
	"c8zthw": "TRON",
	"bki2u2": "TRST",
	"c2cfa2": "TRUE",
	"bh7r6h": "TRUK",
	"bki2zr": "TRUS",
	"bki33m": "TSPC",
	"bh72cw": "TUGU",
	"c9pfpr": "TYRE",
	"bv1qlh": "UANG",
	"bt7nnm": "UCID",
	"cbazxm": "UDNG",
	"bxjur7": "UFOE",
	"bki36h": "ULTJ",
	"bki39c": "UNIC",
	"bzv6mw": "UNIQ",
	"bn9pjc": "UNSP",
	"ccanww": "UNTD",
	"bn9pm7": "UNTR",
	"bn9pp2": "UNVR",
	"bo5fsm": "URBN",
	"c2ruww": "UVCR",
	"c8sn8m": "VAST",
	"cesblh": "VERN",
	"bx3pp2": "VICI",
	"bki3nm": "VICO",
	"bki3qh": "VINS",
	"cchqzr": "VISI",
	"bki45r": "VIVA",
	"ca2e9c": "VKTR",
	"bki4bh": "VOKS",
	"bki4k2": "VRNA",
	"c89txm": "VTNY",
	"bki4mw": "WAPO",
	"bki4pr": "WEGE",
	"bki4sm": "WEHA",
	"c4bevh": "WGSH",
	"bki76h": "WICO",
	"ca9dkr": "WIDI",
	"bx86dm": "WIFI",
	"bki79c": "WIIM",
	"bn9q77": "WIKA",
	"c8isf2": "WINE",
	"c5yu77": "WINR",
	"bn9qa2": "WINS",
	"c5o9z2": "WIRG",
	"bxjkec": "WMUU",
	"bki7hw": "WOMF",
	"bki7kr": "WOOD",
	"bsnwf2": "WOWS",
	"bki7z2": "WSBP",
	"bn9r9c": "WTON",
	"bnehec": "YELO",
	"cfl49c": "YOII",
	"bki8bh": "YPAS",
	"bki7nm": "YULE",
	"cgaarw": "YUPI",
	"c7x3im": "ZATA",
	"bhacdm": "ZBRA",
	"bki7qh": "ZINC",
	"bo5fyc": "ZONE",
	"c1c1kr": "ZYRX",
}

// GetIDXStock looks up an Indonesian stock by ticker symbol
func GetIDXStock(ticker string) (IDXStock, bool) {
	stock, ok := IDXStocks[ticker]
	return stock, ok
}

// GetIDXStockID returns the MSN ID for a ticker, or empty string if not found
func GetIDXStockID(ticker string) string {
	if stock, ok := IDXStocks[ticker]; ok {
		return stock.ID
	}
	return ""
}

// GetIDXTicker returns the ticker symbol for an MSN ID
func GetIDXTicker(id string) string {
	return IDXIDToTicker[id]
}

// GetAllIDXStocks returns all IDX stocks
func GetAllIDXStocks() map[string]IDXStock {
	return IDXStocks
}

// GetIDXStockCount returns the total number of IDX stocks
func GetIDXStockCount() int {
	return len(IDXStocks)
}
